force-app/main/default/objects/Account/fields/Candidate_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate Checklist</label>
    <referenceTo>Candidate_Checklist__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate_Checklist__c/Candidate_Checklist__c.object-meta.xml
<CustomObject>
    <label>Candidate Checklist</label>
    <nameField>
        <displayFormat>CCN-{00000}</displayFormat>
        <label>Candidate Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Checklist__c/fields/Candidate_Name__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Candidate Checklists</relationshipLabel>
    <relationshipName>Candidate_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChecklistConfiguration__mdt/ChecklistConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>Checklist Configuration</label>
    <pluralLabel>Checklist Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NCS_ChecklistTest.cls
@IsTest
public class NCS_ChecklistTest {
    @IsTest(SeeAllData=true)
    public static void RunTest()
    {
        ChecklistConfiguration__mdt config = [SELECT Id FROM ChecklistConfiguration__mdt WHERE DeveloperName = 'Opener_Checklist' LIMIT 1];
        Transaction__c t = [SELECT Id FROM Transaction__c LIMIT 1];
        NCS_Checklist.Checklist checklist = NCS_Checklist.generateChecklist(config.Id, t.Id);
        ChecklistController.getChecklist(t.Id, config.Id, null);
    }

    @IsTest(SeeAllData=true)
    public static void RunTest2()
    {
        ChecklistConfiguration__mdt config = [SELECT Id FROM ChecklistConfiguration__mdt WHERE DeveloperName = 'ARIVE_Account_Setup' LIMIT 1];
        Account a = [SELECT Id,PersonContactId FROM Account WHERE PersonContactId != null  LIMIT 1];
        Candidate_Checklist__c checklistCandidate = new Candidate_Checklist__c(Candidate_Name__c=a.Id);
        insert checklistCandidate;
        a.Candidate_Checklist__c = checklistCandidate.Id;
        update a;
        NCS_Checklist.Checklist checklist = ChecklistController.getChecklist(a.Id, config.Id, 'Candidate_Checklist__c');

    }
 
}