force-app/main/default/objects/Account/fields/Realtor_Group__c.field-meta.xml
<CustomField>
    <fullName>Realtor_Group__c</fullName>
    <label>Realtor Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>The Nickley Group</fullName>
            </value>
            <value>
                <fullName>EXP Realty Melbourne</fullName>
            </value>
            <value>
                <fullName>Coastal Real Estate Professionals</fullName>
            </value>
            <value>
                <fullName>Nickley ISA&apos;s</fullName>
            </value>
            <value>
                <fullName>SERHANT - ORL</fullName>
            </value>
            <value>
                <fullName>Wemert Group</fullName>
            </value>
            <value>
                <fullName>Premier Group At Compass</fullName>
            </value>
            <value>
                <fullName>Homes by Cusi</fullName>
            </value>
            <value>
                <fullName>Champagne &amp; Parisi Real Estate</fullName>
            </value>
            <value>
                <fullName>Rinker Realty</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_To_Account__c/User_To_Account__c.object-meta.xml
<CustomObject>
    <label>User To Account</label>
    <nameField>
        <displayFormat>UTA-{0000}</displayFormat>
        <label>User To Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User To Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_To_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>User To Accounts</relationshipLabel>
    <relationshipName>User_To_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_To_Account__c/fields/Realtor_Group__c.field-meta.xml
<CustomField>
    <fullName>Realtor_Group__c</fullName>
    <formula>TEXT(Account__r.Realtor_Group__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Realtor Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_To_Account__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_To_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WemertIntakeFormController.cls
public without sharing class WemertIntakeFormController {

    @AuraEnabled
    public static List<Account> getRealtorAccounts() {
        return [SELECT Id, Name, FirstName, LastName FROM Account WHERE Realtor_Group__c = 'Wemert Group'];
    }
    
    @AuraEnabled 
    public static List<User> getLoanOfficers(String accountId) {
        
        Set<Id> userIds = new Set<Id>();
        List<User_To_Account__c> userToAccounts = [SELECT Id, User__c FROM User_To_Account__c WHERE Account__c = :accountId AND Active__c = TRUE];
        for (User_To_Account__c uta : userToAccounts) {
            userIds.add(uta.User__c);
        }
        
        return [
            SELECT Id, Name, FirstName, LastName, Phone, Email, Headshot_URL__c
            FROM User
            WHERE Id IN :userIds
            AND IsActive = TRUE
            ORDER BY Name
        ];
    }
}