force-app/main/default/objects/Account/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__mdt/Alert__mdt.object-meta.xml
<CustomObject>
    <label>Alert</label>
    <pluralLabel>Alerts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Alert__mdt/fields/Complete_Message__c.field-meta.xml
<CustomField>
    <fullName>Complete_Message__c</fullName>
    <label>Complete Message</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__mdt/fields/Incomplete_Message__c.field-meta.xml
<CustomField>
    <fullName>Incomplete_Message__c</fullName>
    <label>Incomplete Message</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alert_Field__mdt/Alert_Field__mdt.object-meta.xml
<CustomObject>
    <label>Alert Field</label>
    <pluralLabel>Alert Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/Alert_Field__mdt/fields/Alert__c.field-meta.xml
<CustomField>
    <fullName>Alert__c</fullName>
    <label>Alert</label>
    <referenceTo>Alert__mdt</referenceTo>
    <relationshipLabel>Alert Fields</relationshipLabel>
    <relationshipName>Alert_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Alert_Field__mdt/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/BPS__c.field-meta.xml
<CustomField>
    <fullName>BPS__c</fullName>
    <label>BPS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Clear_to_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Clear_to_Close_Date__c</fullName>
    <label>Clear to Close Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>Lead source, mapped from lead object</description>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reach In Market Dialer</fullName>
            </value>
            <value>
                <fullName>Realtor Referral</fullName>
            </value>
            <value>
                <fullName>Past Client</fullName>
            </value>
            <value>
                <fullName>Personal Referral</fullName>
            </value>
            <value>
                <fullName>Nickley Listing Credit</fullName>
            </value>
            <value>
                <fullName>Previous Client Referral</fullName>
            </value>
            <value>
                <fullName>Google_Organic</fullName>
                <label>Google Organic</label>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Zillow</fullName>
            </value>
            <value>
                <fullName>Nickley ISA</fullName>
            </value>
            <value>
                <fullName>Tik Tok</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>VM Refinance</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Facebook - Landing Refi</fullName>
            </value>
            <value>
                <fullName>Facebook Text Quote</fullName>
            </value>
            <value>
                <fullName>Facebook Lead Ad</fullName>
            </value>
            <value>
                <fullName>Consumer Webinar</fullName>
            </value>
            <value>
                <fullName>Instagram-Linktree</fullName>
            </value>
            <value>
                <fullName>Facebook-Linktree</fullName>
            </value>
            <value>
                <fullName>Youtube-Linktree</fullName>
            </value>
            <value>
                <fullName>Tiktok-Linktree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_1st__c</fullName>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AlertControllerTest.cls
@isTest
public class AlertControllerTest {
	@isTest
    public static void runTest(){               
        Account acc = (Account)TDF.createSObject('Account', new Map<String,Object>{
                'FirstName' => 'Test',
                'LastName' => 'Somebody',
                'PersonEmail' => 'test@email.com',
                'RecordTypeId' => [SELECT Id, Name FROM RecordType WHERE Name = 'Person Account'].Id
        });
        Transaction__c o = new Transaction__c(Borrower_Name__c=acc.Id,Name='TodaysTest',Clear_to_Close_Date__c=date.today().addMonths(1), BPS__c=0.10, Loan_Amount_1st__c=250000,Lead_Source__c='Website - Purchase');
        insert o;
        Alert__mdt alert = [SELECT Id, Title__c, Complete_Message__c, Incomplete_Message__c, (SELECT Id, Alert__c, API_Name__c, Title__c FROM Alert_Fields__r) FROM Alert__mdt LIMIT 1];
        AlertController.getEmptyFieldsFromLoan(o.Id,alert.Id);
        AlertController.runTest();
    }
}