force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <description>List of conditions in order to close loan</description>
    <label>Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Include_In_Email__c.field-meta.xml
<CustomField>
    <fullName>Include_In_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include In Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/IncludeInEmail__c.field-meta.xml
<CustomField>
    <fullName>IncludeInEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include In Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
                <isActive>false</isActive>
                <label>Waiting on someone else</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionCondition.cls
public with sharing class TransactionCondition extends PersistentObject {
    @AuraEnabled
    public Condition__c data;

    @AuraEnabled
    public List<ContentVersion> contentVersions;

    public TransactionCondition(Condition__c data) {
        this.data = data;
    }

    public void setStatus(String status) {
        this.data.Status__c = status;
    }

    public void setIncludedInEmail(Boolean isIncluded) {
        Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Condition__c').getDescribe().fields.getMap();
        if (fieldMap.containsKey('Include_In_Email__c')) {
            this.data.put('Include_In_Email__c', isIncluded);
        }
        if (fieldMap.containsKey('IncludeInEmail__c')) {
            this.data.put('IncludeInEmail__c', isIncluded);
        }
    }

    public override void persist() {
        if (!Schema.SObjectType.Condition__c.isUpdateable() || !Schema.SObjectType.Condition__c.isCreateable()) {
            return;
        }
        if (this.getPersistenceStrategy() == null) {
            Database.upsert(this.data, true, AccessLevel.USER_MODE);
        } else {
            this.getPersistenceStrategy().persist(data);
        }
    }
}