force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <description>List of conditions in order to close loan</description>
    <label>Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Condition_Satisfaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Condition_Satisfaction_Date__c</fullName>
    <label>Condition Satisfaction Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Is_Condition_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Condition_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Condition Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
                <isActive>false</isActive>
                <label>Waiting on someone else</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/UW_Notes__c.field-meta.xml
<CustomField>
    <fullName>UW_Notes__c</fullName>
    <label>UW Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/UWM_Condition_Id__c.field-meta.xml
<CustomField>
    <fullName>UWM_Condition_Id__c</fullName>
    <externalId>true</externalId>
    <label>UWM Condition Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TRID Application</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Submission Form Complete</label>
            </value>
            <value>
                <fullName>Disclosures Out</fullName>
            </value>
            <value>
                <fullName>Pre-Processing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Waiting On Loan Officer</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Re-Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PC Review</fullName>
            </value>
            <value>
                <fullName>Post-Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UWM_Conditions_API_Res_Model.cls
/**
 * Created by toma on 11/9/2022.
 */

public with sharing class UWM_Conditions_API_Res_Model {
    public List<ConditionsGroup> conditionGroups;
    public List<Condition> clearedConditions;
    public class Condition{
        public String id; //UWM_Id__c
        public String conditionCategory; //Category__c
        public String conditionDescription; //UWM_Description__c
        public Boolean isConditionUploaded; //?? Uploaded__c
        public Datetime conditionSatisfactionDate;//?? Sat_date__c
        public String conditionGroup;//Group++c
        public String displayValueId;

        public Condition__c  convertToClientNeed(String loanId, String loanNumber, String conditionType){
            String uwNotes;
            String conditionsStatus;
            if(this.conditionDescription.contains('*')){
                uwNotes = this.conditionDescription.split('\\*+')[1];
            }
            if(!String.isBlank(conditionType) && conditionType == 'Cleared'){
                conditionsStatus = 'Cleared';
            } else {
                conditionsStatus = this.isConditionUploaded ? 'Submitted' : 'New';
            }
            return new Condition__c (
                UWM_Condition_Id__c = this.id,
                Status__c = conditionsStatus,
                UWM_Description__c = this.conditionDescription,
                Description__c = this.conditionDescription,
                UW_Notes__c = uwNotes != null ? uwNotes : '',
                Is_Condition_Uploaded__c = this.isConditionUploaded,
                Condition_Satisfaction_Date__c = this.conditionSatisfactionDate,
                Completed_Date__c  = this.conditionSatisfactionDate?.date(),
                Condition_Group_Key__c = this.conditionGroup,
                Category__c = this.conditionCategory,
                Transaction__c  = loanId,
                UWMReferenceId__c = this.displayValueId
            );
        }
    }
    public class ConditionsGroup{
        public String key;
        public Integer countItems;
        public Integer uploadedConditionsCount;
        public List<Condition> conditions;
    }

    public void flatten(){
        for(ConditionsGroup condGroup : conditionGroups){
            for(Condition condition : condGroup.conditions){
                condition.conditionGroup = condGroup.key;
            }
        }
    }
}