force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <description>List of conditions in order to close loan</description>
    <label>Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jr. Processor</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Loan Officer</fullName>
            </value>
            <value>
                <fullName>Loan Coordinator</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Post Closing</fullName>
            </value>
            <value>
                <fullName>Generic Document Portal Upload</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
                <isActive>false</isActive>
                <label>LC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Action__c/User_Action__c.object-meta.xml
<CustomObject>
    <label>User Action</label>
    <nameField>
        <displayFormat>UA-{00000000}</displayFormat>
        <label>User Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Action__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>User Actions</relationshipLabel>
    <relationshipName>UserActions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Action__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>User Actions</relationshipLabel>
    <relationshipName>UserActions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Action__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Approval Sent</fullName>
            </value>
            <value>
                <fullName>Proposed Refinance Sent</fullName>
            </value>
            <value>
                <fullName>Loan Conditions Email Sent</fullName>
            </value>
            <value>
                <fullName>Realtor Intake Form Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Action__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserActionController.cls
public with sharing class UserActionController {
    private static final String USER_ACTION_OBJECT = 'User_Action__c';

    @AuraEnabled
    public static void saveUserInteraction(Map<String, Object> params) {
        try {
            Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
            if (!globalDescribe.containsKey(USER_ACTION_OBJECT)) {
                System.debug(LoggingLevel.INFO, 'User action object not available. Params: ' + JSON.serialize(params));
                return;
            }

            Schema.SObjectType actionType = globalDescribe.get(USER_ACTION_OBJECT);
            Map<String, Schema.SObjectField> fieldsMap = actionType.getDescribe().fields.getMap();
            SObject actionRecord = actionType.newSObject();

            putIfPresent(actionRecord, fieldsMap, 'Transaction__c', params.get('transactionId'));
            putIfPresent(actionRecord, fieldsMap, 'Condition__c', params.get('conditionId'));
            putIfPresent(actionRecord, fieldsMap, 'Type__c', params.get('type'));
            putIfPresent(actionRecord, fieldsMap, 'User__c', UserInfo.getUserId());

            Database.insert(actionRecord, true);
        } catch (Exception e) {
            System.debug(LoggingLevel.ERROR, 'Error saving user action: ' + e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    private static void putIfPresent(SObject target, Map<String, Schema.SObjectField> fieldsMap, String fieldName, Object value) {
        if (value != null && fieldsMap.containsKey(fieldName)) {
            target.put(fieldName, value);
        }
    }
}