force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <description>List of conditions in order to close loan</description>
    <label>Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Comment__c/Condition_Comment__c.object-meta.xml
<CustomObject>
    <label>Condition Comment</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Condition Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition_Comment__c/fields/Comment_Text__c.field-meta.xml
<CustomField>
    <fullName>Comment_Text__c</fullName>
    <description>Comment text</description>
    <label>Comment Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Condition_Comment__c/fields/Condition__c.field-meta.xml
<CustomField>
    <fullName>Condition__c</fullName>
    <description>Condition</description>
    <label>Condition</label>
    <referenceTo>Condition__c</referenceTo>
    <relationshipLabel>Condition Comments</relationshipLabel>
    <relationshipName>Condition_Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Condition_Comment__c/fields/Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Name__c</fullName>
    <description>Created by name</description>
    <formula>IF(
    Portal_Comment__c,
    Condition__r.Transaction__r.Borrower_First_Name__c + &apos; &apos; + Condition__r.Transaction__r.Borrower_Last_Name__c,
    CreatedBy.FirstName + &apos; &apos; + CreatedBy.LastName
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created By Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Condition_Comment__c/fields/Portal_Comment__c.field-meta.xml
<CustomField>
    <fullName>Portal_Comment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Portal comment</description>
    <label>Portal Comment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Condition_Comment__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Public</description>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Condition_Comment__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Read</description>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Borrower_Email__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Email__c</fullName>
    <formula>Borrower_Name__r.PersonEmail</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrower Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Portal_Hash_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Portal_Hash_Parameter__c</fullName>
    <label>Portal Hash Parameter</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Processor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConditionCommentRepository.cls
public with sharing class ConditionCommentRepository {
    private static ConditionCommentRepository self;

    public static ConditionCommentRepository getInstance() {
        if (self == null) {
            self = new ConditionCommentRepository();
        }
        return self;
    }

    public List<Condition_Comment__c> selectByConditionId(Id conditionId, Boolean includePrivateComments) {
        if (conditionId == null) {
            return new List<Condition_Comment__c>();
        }

        if (includePrivateComments) {
            return [
                SELECT
                    Id,
                    Condition__c,
                    Condition__r.Name,
                    Condition__r.Description__c,
                    Condition__r.Assigned_To__c,
                    Condition__r.Transaction__c,
                    Condition__r.Transaction__r.Name,
                    Condition__r.Transaction__r.Borrower_Email__c,
                    Condition__r.Transaction__r.Portal_Hash_Parameter__c,
                    Condition__r.Transaction__r.Processor__r.Name,
                    Condition__r.Transaction__r.Processor__r.FirstName,
                    Condition__r.Transaction__r.Processor__r.LastName,
                    Condition__r.Transaction__r.Processor__r.Title,
                    Condition__r.Transaction__r.Processor__r.Phone,
                    Condition__r.Transaction__r.Processor__r.MobilePhone,
                    Condition__r.Transaction__r.Processor__r.Email,
                    Condition__r.Transaction__r.Processor__r.Fax,
                    Condition__r.Transaction__r.Processor__r.NMLS__c,
                    Condition__r.Transaction__r.Processor__r.Headshot_URL__c,
                    Comment_Text__c,
                    Portal_Comment__c,
                    Public__c,
                    Read__c,
                    Created_By_Name__c,
                    CreatedDate
                FROM Condition_Comment__c
                WHERE Condition__c = :conditionId
                ORDER BY CreatedDate ASC
            ];
        }

        return [
            SELECT
                Id,
                Condition__c,
                Condition__r.Name,
                Condition__r.Description__c,
                Condition__r.Assigned_To__c,
                Condition__r.Transaction__c,
                Condition__r.Transaction__r.Name,
                Condition__r.Transaction__r.Borrower_Email__c,
                Condition__r.Transaction__r.Portal_Hash_Parameter__c,
                Condition__r.Transaction__r.Processor__r.Name,
                Condition__r.Transaction__r.Processor__r.FirstName,
                Condition__r.Transaction__r.Processor__r.LastName,
                Condition__r.Transaction__r.Processor__r.Title,
                Condition__r.Transaction__r.Processor__r.Phone,
                Condition__r.Transaction__r.Processor__r.MobilePhone,
                Condition__r.Transaction__r.Processor__r.Email,
                Condition__r.Transaction__r.Processor__r.Fax,
                Condition__r.Transaction__r.Processor__r.NMLS__c,
                Condition__r.Transaction__r.Processor__r.Headshot_URL__c,
                Comment_Text__c,
                Portal_Comment__c,
                Public__c,
                Read__c,
                Created_By_Name__c,
                CreatedDate
            FROM Condition_Comment__c
            WHERE Condition__c = :conditionId
            AND Public__c = true
            ORDER BY CreatedDate ASC
        ];
    }

    public Condition_Comment__c selectById(Id commentId) {
        if (commentId == null) {
            return null;
        }

        List<Condition_Comment__c> comments = [
            SELECT
                Id,
                Condition__c,
                Condition__r.Name,
                Condition__r.Description__c,
                Condition__r.Assigned_To__c,
                Condition__r.Transaction__c,
                Condition__r.Transaction__r.Name,
                Condition__r.Transaction__r.Borrower_Email__c,
                Condition__r.Transaction__r.Portal_Hash_Parameter__c,
                Condition__r.Transaction__r.Processor__r.Name,
                Condition__r.Transaction__r.Processor__r.FirstName,
                Condition__r.Transaction__r.Processor__r.LastName,
                Condition__r.Transaction__r.Processor__r.Title,
                Condition__r.Transaction__r.Processor__r.Phone,
                Condition__r.Transaction__r.Processor__r.MobilePhone,
                Condition__r.Transaction__r.Processor__r.Email,
                Condition__r.Transaction__r.Processor__r.Fax,
                Condition__r.Transaction__r.Processor__r.NMLS__c,
                Condition__r.Transaction__r.Processor__r.Headshot_URL__c,
                Comment_Text__c,
                Portal_Comment__c,
                Public__c,
                Read__c,
                Created_By_Name__c,
                CreatedDate
            FROM Condition_Comment__c
            WHERE Id = :commentId
            LIMIT 1
        ];
        return comments.isEmpty() ? null : comments[0];
    }
}