force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <description>List of conditions in order to close loan</description>
    <label>Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Deferred</fullName>
                <isActive>false</isActive>
                <label>Deferred</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
                <isActive>false</isActive>
                <label>Waiting on someone else</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Transaction_Condition_Reference__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Condition_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Condition Reference</label>
    <referenceTo>Transaction_Condition_Reference__c</referenceTo>
    <relationshipLabel>Conditions</relationshipLabel>
    <relationshipName>Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jr. Processor</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Loan Officer</fullName>
            </value>
            <value>
                <fullName>Loan Coordinator</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Post Closing</fullName>
            </value>
            <value>
                <fullName>Generic Document Portal Upload</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
                <isActive>false</isActive>
                <label>LC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/Transaction_Condition_Reference__c.object-meta.xml
<CustomObject>
    <label>Transaction Condition Reference</label>
    <nameField>
        <displayFormat>TCR-{0000}</displayFormat>
        <label>Transaction Condition Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Condition References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Condition_Category__c.field-meta.xml
<CustomField>
    <fullName>Condition_Category__c</fullName>
    <label>Condition Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Appraisal</fullName>
            </value>
            <value>
                <fullName>Assets</fullName>
            </value>
            <value>
                <fullName>REO</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Disclosure</fullName>
            </value>
            <value>
                <fullName>Flood</fullName>
            </value>
            <value>
                <fullName>Escrow</fullName>
            </value>
            <value>
                <fullName>Payoff Demand</fullName>
            </value>
            <value>
                <fullName>HOA</fullName>
            </value>
            <value>
                <fullName>HOI</fullName>
            </value>
            <value>
                <fullName>Approval</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>Income/Employment</fullName>
            </value>
            <value>
                <fullName>Liabilities</fullName>
            </value>
            <value>
                <fullName>LOX</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
            <value>
                <fullName>No Category</fullName>
            </value>
            <value>
                <fullName>Post Closing</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
            <value>
                <fullName>Title</fullName>
            </value>
            <value>
                <fullName>WVOE</fullName>
            </value>
            <value>
                <fullName>EMD</fullName>
            </value>
            <value>
                <fullName>LOE</fullName>
            </value>
            <value>
                <fullName>Disclosures</fullName>
            </value>
            <value>
                <fullName>VOM</fullName>
            </value>
            <value>
                <fullName>VOR</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>Do Not Use</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Condition_Group_Key__c.field-meta.xml
<CustomField>
    <fullName>Condition_Group_Key__c</fullName>
    <label>Condition Group Key</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Master</fullName>
            </value>
            <value>
                <fullName>Senior Underwriter (PTD)</fullName>
            </value>
            <value>
                <fullName>Underwriter II (PTD)</fullName>
            </value>
            <value>
                <fullName>Project Review (PTD)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <externalId>true</externalId>
    <label>Reference Id</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Officer</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Initial Submission</fullName>
            </value>
            <value>
                <fullName>Initial Submission Optional</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Vendor Standard</fullName>
            </value>
            <value>
                <fullName>Post Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionConditionTriggerHandler.cls
public with sharing class TransactionConditionTriggerHandler {
    public static Boolean isUWMSyncEnabled = false;
    private final List<Condition__c> newConditions;
    private final Map<Id, Condition__c> oldConditionsMap;

    /**
     * @description Constructor
     */
    public TransactionConditionTriggerHandler() {
        this.newConditions = (List<Condition__c>) Trigger.new;
        this.oldConditionsMap = (Map<Id,Condition__c>) Trigger.oldMap;
    }

    /**
     * @description Before update handler method
     */
    public void handleBeforeUpdate(){
        updateStatusAndDescription();
    }

    /**
     * @description After insert handler method
     */
    public void handleAfterInsert(){
        processReferences();
    }

    /**
     * @description This method updates status and description of new conditions.
     * It prevents from changing status of new conditions to New if old conditions status is not New.
     * It also prevents from changing description of new conditions
     * if old conditions description is not equal to new conditions description and condition has
     * condition reference record lookup set.
     */
    private void updateStatusAndDescription(){
        if(!isUWMSyncEnabled){
            return;
        }

        for(Condition__c newCond : this.newConditions){
            Condition__c oldCondition = this.oldConditionsMap.get(newCond.Id);
            if(
                    newCond.Status__c == 'New'
                            && oldCondition.Status__c != 'New'
                            && !String.isBlank(oldCondition.Status__c)
            ){
                newCond.Status__c = oldCondition.Status__c;
            }
            if(
                    oldCondition.Description__c != null
                            && newCond.Description__c != oldCondition.Description__c
                            && !String.isBlank(newCond.Transaction_Condition_Reference__c)
            ){
                newCond.Description__c = oldCondition.Description__c;
            }
        }
    }

    /**
     * @description This method processes references for new conditions.
     * It gathers unique UWM reference codes from new conditions. If existing reference
     * do not contains UWM reference code from new conditions, it creates new reference.
     * It updates new conditions with reference id.
     * It updates existing references with new condition group key if it is not set and condition has group key.
     * Set Group Key on a new reference if condition has group key.
     */
    private void processReferences(){
        List<Condition__c> conditionsToUpdate = new List<Condition__c>();
        Map<String,List<Condition__c>> conditionsToUpdateWithNewlyInsertedReferences = new Map<String,List<Condition__c>>();

        Set<String> uniqueUWMConditionIds = gatherUniqueReferences();
        Map<String, Transaction_Condition_Reference__c> searchReferencesMap = getCurrentReferences(uniqueUWMConditionIds);
        fillConditionsToUpdate(conditionsToUpdate, searchReferencesMap, conditionsToUpdateWithNewlyInsertedReferences);

        if(!conditionsToUpdateWithNewlyInsertedReferences.isEmpty()){
            Map<String, Transaction_Condition_Reference__c> insertedReferencesMap = insertNewReferences(conditionsToUpdateWithNewlyInsertedReferences);
            fillConditionsWithNewReferenceId(conditionsToUpdate, conditionsToUpdateWithNewlyInsertedReferences, insertedReferencesMap);
        }
        updateCurrentReferencesWithGroupKey(searchReferencesMap);
        if (Schema.SObjectType.Condition__c.fields.Transaction_Condition_Reference__c.isUpdateable()) {
            Database.update(conditionsToUpdate, false, System.AccessLevel.SYSTEM_MODE);
        }
    }

    /**
     * @description This method inserts new references if they are not exist and
     * set group key if it is not set and condition has group key.
     * @param conditionsToUpdateWithNewlyInsertedReferences - map of conditions
     * to update with newly inserted references as keys
     * @return Map<String,Loan_Condition_Reference__c> referencesToInsert
     */
    private Map<String,Transaction_Condition_Reference__c> insertNewReferences(
            Map<String,List<Condition__c>> conditionsToUpdateWithNewlyInsertedReferences
    ){
        Map<String,Transaction_Condition_Reference__c> referencesToInsert = new Map<String,Transaction_Condition_Reference__c>();
        for(String referenceId : conditionsToUpdateWithNewlyInsertedReferences.keySet()){
            String conditionGroupKey;
            for(Condition__c condition : conditionsToUpdateWithNewlyInsertedReferences.get(referenceId)){
                if(!String.isBlank(condition.Condition_Group_Key__c)) {
                    conditionGroupKey = condition.Condition_Group_Key__c;
                    break;
                }
            }
            Transaction_Condition_Reference__c reference = new Transaction_Condition_Reference__c(
                    Reference_Id__c = referenceId,
                    Condition_Group_Key__c = conditionGroupKey
            );
            referencesToInsert.put(reference.Reference_Id__c, reference);
        }
        insert referencesToInsert.values();
        return referencesToInsert;
    }

    /**
    * @description This method fills conditions with created reference id
    * @param conditionsToUpdate - list of conditions to update
    * @param conditionsToUpdateWithNewlyInsertedReferences - map of conditions
    * @param insertedReferencesMap - map of inserted references
     */
    private void fillConditionsWithNewReferenceId(
            List<Condition__c> conditionsToUpdate,
            Map<String,List<Condition__c>> conditionsToUpdateWithNewlyInsertedReferences,
            Map<String,Transaction_Condition_Reference__c> insertedReferencesMap
    ){
        for(String referenceId : conditionsToUpdateWithNewlyInsertedReferences.keySet()){
            for(Condition__c condition : conditionsToUpdateWithNewlyInsertedReferences.get(referenceId)){
                Condition__c clonedCondition = condition.clone(true, true, false, false);
                clonedCondition.Transaction_Condition_Reference__c = insertedReferencesMap.get(referenceId).Id;
                conditionsToUpdate.add(clonedCondition);
            }
        }
    }

    /**
    * @description This method creates a list of conditions to update
     * and a map of conditions to update with reference codes as keys
    * @param conditionsToUpdate - list of conditions to update
    * @param searchReferencesMap - map of existing references
    * @param conditionsToUpdateWithNewlyInsertedReferences - map of conditions
     */
    private void fillConditionsToUpdate(
            List<Condition__c> conditionsToUpdate,
            Map<String,Transaction_Condition_Reference__c> searchReferencesMap,
            Map<String,List<Condition__c>> conditionsToUpdateWithNewlyInsertedReferences
    ){
        for(Condition__c condition : this.newConditions) {
            if(String.isBlank(condition.UWMReferenceId__c)) {
                continue;
            }

            String referenceCode = getConditionReferenceCode(condition);
            Condition__c clonedCondition = condition.clone(true, true, false, false);
            if(searchReferencesMap.containsKey(referenceCode)){
                clonedCondition.Transaction_Condition_Reference__c = searchReferencesMap.get(referenceCode).Id;
                conditionsToUpdate.add(clonedCondition);
            } else {
                if(conditionsToUpdateWithNewlyInsertedReferences.get(referenceCode) == null) {
                    conditionsToUpdateWithNewlyInsertedReferences.put(referenceCode, new List<Condition__c>());
                }
                conditionsToUpdateWithNewlyInsertedReferences.get(referenceCode).add(condition);
            }
        }
    }

    /**
    * @description This method current references with group keys
    * if they are not set and condition has group key.
    * @param searchReferencesMap - map of existing references
     */
    private void updateCurrentReferencesWithGroupKey(
            Map<String,Transaction_Condition_Reference__c> searchReferencesMap
    ){
        Boolean referencesHasChanges = false;

        if (searchReferencesMap.isEmpty()) {
            return;
        }

        for(Condition__c condition : this.newConditions) {
            if(String.isBlank(condition.Condition_Group_Key__c)) {
                continue;
            }

            String referenceCode = getConditionReferenceCode(condition);
            if(searchReferencesMap.containsKey(referenceCode) && String.isBlank(searchReferencesMap.get(referenceCode).Condition_Group_Key__c)){
                searchReferencesMap.get(referenceCode).Condition_Group_Key__c = condition.Condition_Group_Key__c;
                referencesHasChanges = true;
            }
        }
        if (referencesHasChanges) {
            update searchReferencesMap.values();
        }
    }

    /**
    * @description This method get current references by set of reference codes
    * @param uniqueUWMConditionIds - set of reference codes
    * @return searchReferences - map of existing references
     */
    private Map<String,Transaction_Condition_Reference__c> getCurrentReferences(Set<String> uniqueUWMConditionIds){
        Map<String,Transaction_Condition_Reference__c> searchReferences = new Map<String, Transaction_Condition_Reference__c>();
        List<Transaction_Condition_Reference__c> referencesThatAlreadyExist = [
                SELECT Id, Reference_Id__c, Condition_Category__c, Type__c, Condition_Group_Key__c
                FROM Transaction_Condition_Reference__c
                WHERE Reference_Id__c IN: uniqueUWMConditionIds
                WITH USER_MODE
        ];
        for(Transaction_Condition_Reference__c reference : referencesThatAlreadyExist){
            searchReferences.put(reference.Reference_Id__c, reference);
        }
        return searchReferences;
    }

    /**
    * @description This method gather unique reference codes
    * @return uniqueUWMConditionIds - set of reference codes
     */
    private Set<String> gatherUniqueReferences(){
        Set<String> uniqueUWMConditionIds = new Set<String>();
        for(Condition__c condition : this.newConditions){
            if(String.isBlank(condition.UWMReferenceId__c)){
                continue;
            }
            uniqueUWMConditionIds.add(getConditionReferenceCode(condition));
        }
        return uniqueUWMConditionIds;
    }

    /**
    * @description This method returns reference code from condition
    * @param condition - condition
    * @return string with reference code
    */
    private String getConditionReferenceCode(Condition__c condition){
        return condition.UWMReferenceId__c;
    }
    
    // TODO: replace. 
    // Couldn't find source tests for this one. Not sure if methods used somewhere, 
    // didn't want to break anything if they do
    public static void testCoverage() {
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
          i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;      
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
          i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;    
                i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
          i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;    
    }
}