force-app/main/default/objects/Condition__c/Condition__c.object-meta.xml
<CustomObject>
    <description>List of conditions in order to close loan</description>
    <label>Condition</label>
    <nameField>
        <label>Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jr. Processor</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Loan Officer</fullName>
            </value>
            <value>
                <fullName>Loan Coordinator</fullName>
            </value>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Post Closing</fullName>
            </value>
            <value>
                <fullName>Generic Document Portal Upload</fullName>
            </value>
            <value>
                <fullName>LC</fullName>
                <isActive>false</isActive>
                <label>LC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UWMConditionTypeDynamicPicklist.cls
/**
 * Dynamic design-time picklist for `ConditionsViewer`.
 */
public with sharing class UWMConditionTypeDynamicPicklist extends VisualEditor.DynamicPickList {
    public override VisualEditor.DataRow getDefaultValue() {
        return null;
    }

    public override VisualEditor.DynamicPickListRows getValues() {
        VisualEditor.DynamicPickListRows values = new VisualEditor.DynamicPickListRows();
        List<Schema.PicklistEntry> picklistEntries = Condition__c.Type__c.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry entry : picklistEntries) {
            values.addRow(new VisualEditor.DataRow(entry.getLabel(), entry.getValue()));
        }
        return values;
    }
}