force-app/main/default/objects/Enhanced_Note__c/Enhanced_Note__c.object-meta.xml
<CustomObject>
    <label>Enhanced Note</label>
    <nameField>
        <displayFormat>NOTE-{000000000}</displayFormat>
        <label>Enhanced Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enhanced Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enhanced_Note__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>130000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Enhanced_Note__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Enhanced Notes</relationshipLabel>
    <relationshipName>Enhanced_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Notes_JSON__c.field-meta.xml
<CustomField>
    <fullName>Lead_Notes_JSON__c</fullName>
    <label>Lead Notes JSON</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LeadNotesFormControllerTest.cls
@isTest
public with sharing class LeadNotesFormControllerTest {
	@TestSetup
	static void makeData(){
		Lead testLead = new Lead(
			FirstName = 'Test',
			LastName = Datetime.now().toString()
		);

		insert testLead;
	}
    @isTest
	static void getNotesTest() {
		Lead testLead = [SELECT Id FROM Lead ORDER BY CreatedDate DESC LIMIT 1];
		String testLeadNotes = 'Test Lead Notes on: ' + Datetime.now().toString();
		testLead.Lead_Notes_JSON__c = testLeadNotes;
	
		update testLead;

		Test.startTest();
		String actualNotes = LeadNotesFormController.getNotes(testLead.Id);
		Test.stopTest();

		System.assertEquals(testLeadNotes, actualNotes, 'Wrong notes returned');
    } 

	@isTest
	static void saveNotesTest() {
		Lead testLead = [SELECT Id FROM Lead ORDER BY CreatedDate DESC LIMIT 1];
		String testLeadNotes = 'Test Lead Notes on: ' + Datetime.now().toString();
		
		Test.startTest();
		LeadNotesFormController.saveNotes(testLead.Id, testLeadNotes);
		Test.stopTest();

		Lead actualLead = [SELECT Id, Lead_Notes_JSON__c FROM Lead WHERE Id = :testLead.Id];

		System.assertEquals(testLeadNotes, actualLead.Lead_Notes_JSON__c, 'Notes were not set');
	}

	@isTest
	static void createNoteTest() {
		Lead testLead = [SELECT Id, Name FROM Lead ORDER BY CreatedDate DESC LIMIT 1];
		Map<String, String> notesMap = new Map<String, String>{
			'Borrower Name' => testLead.Name
		};
		String notesJSON = JSON.serialize(notesMap);

		Test.startTest();
		LeadNotesFormController.createNote(testLead.Id, notesJSON, notesJSON);
		Test.stopTest();

		Enhanced_Note__c note = [SELECT Id, Body__c FROM Enhanced_Note__c WHERE Lead__c = :testLead.Id ORDER BY CreatedDate DESC LIMIT 1];
	
		System.assertNotEquals(null, note, 'Note should be created');
		System.assertEquals(true, note.Body__c.contains(testLead.name), 'Enhanced Note is not populated correctly');
	}
}