force-app/main/default/objects/Enhanced_Note__c/Enhanced_Note__c.object-meta.xml
<CustomObject>
    <label>Enhanced Note</label>
    <nameField>
        <displayFormat>NOTE-{000000000}</displayFormat>
        <label>Enhanced Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enhanced Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enhanced_Note__c/fields/IsDeleted__c.field-meta.xml
<CustomField>
    <fullName>IsDeleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDeleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EnhancedNotesController.cls
/**
 * Created by J9 on 8/26/2021.
 */

public with sharing class EnhancedNotesController {

    @AuraEnabled
    public static List<Enhanced_Note__c> getNotesRelatedToLoan(String loanId){
        return EnhancedNotesRepository.getInstance().getEnhancedNotedByLoanId(loanId);
    }

    @AuraEnabled
    public static void deleteTargetNote(String recordId){
        Enhanced_Note__c note = new Enhanced_Note__c(Id=recordId, IsDeleted__c=true);
        update note;
    }
    @AuraEnabled
    public static String getLookupField(Id recordId){
        return EnhancedNotesRepository.getLookupField(recordId);
    }

//@AuraEnabled
//    public static String getApplicationName(String recordId, String noteId){
//    String output;
//    if(noteId != null){
//        List<Enhanced_Note__c> name = [SELECT Application__r.Name FROM Enhanced_Note__c WHERE Id=:noteId];
//        output = name[0].Application__r.Name;
//    }else{
//        List<Enhanced_Note__c> name = [SELECT Application__r.Name FROM Enhanced_Note__c WHERE Application__r.Id=:recordId];
//        output = name[0].Application__r.Name;
//    }
//    return output;
//    } 
}