force-app/main/default/objects/Call_Insight__c/Call_Insight__c.object-meta.xml
<CustomObject>
    <label>Call Insight</label>
    <nameField>
        <displayFormat>CI-{0000}</displayFormat>
        <label>Call Insights Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Insights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Insight__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Call Insights</relationshipLabel>
    <relationshipName>Call_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/AI_Score__c.field-meta.xml
<CustomField>
    <fullName>AI_Score__c</fullName>
    <label>AI Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/HighLights__c.field-meta.xml
<CustomField>
    <fullName>HighLights__c</fullName>
    <label>HighLights</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Call Insights</relationshipLabel>
    <relationshipName>Call_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Next_Steps__c.field-meta.xml
<CustomField>
    <fullName>Next_Steps__c</fullName>
    <label>Next Steps</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Recording_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Recording_Start_DateTime__c</fullName>
    <label>Recording Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Salesforce_User__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Call_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Call Insights</relationshipLabel>
    <relationshipName>Call_Insights</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Insight__c/fields/Transcript__c.field-meta.xml
<CustomField>
    <fullName>Transcript__c</fullName>
    <label>Transcript</label>
    <length>90000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Account Name)</relationshipLabel>
    <relationshipName>Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CallInsightListController.cls
public without sharing class CallInsightListController {

    @AuraEnabled
    public static List<Call_Insight__c> getCallInsights(String recordId) {
        
        String whereLocator;
        if (recordId.startsWith('00Q')) {
            whereLocator = 'WHERE Lead__c = :recordId ';
        } else if (recordId.startsWith('001')) {
            whereLocator = 'WHERE Account__c = :recordId ';
        } else {
            whereLocator = 'WHERE Transaction__c = :recordId ';
        } 
        
        return (List<Call_Insight__c>) Database.query(
            'SELECT Id, Name,  Salesforce_User__r.FirstName, Salesforce_User__r.LastName, CreatedDate, AI_Score__c, Direction__c, Duration__c, Title__c, ' +
            'Summary__c, Transcript__c, HighLights__c, Next_Steps__c, ' +
            'Salesforce_User__c, Salesforce_User__r.Name, Recording_Start_DateTime__c ' +
            'FROM Call_Insight__c ' +
             whereLocator + ' ' + 
            'ORDER BY Recording_Start_DateTime__c DESC'
        );
    }
}