force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TRID Application</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Submission Form Complete</label>
            </value>
            <value>
                <fullName>Disclosures Out</fullName>
            </value>
            <value>
                <fullName>Pre-Processing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Waiting On Loan Officer</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Re-Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PC Review</fullName>
            </value>
            <value>
                <fullName>Post-Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/UWM_Loan_Info__c.field-meta.xml
<CustomField>
    <fullName>UWM_Loan_Info__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UWM Loan Info</label>
    <referenceTo>UWM_Loan_Info__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/UWM_Loan_Info_ID__c.field-meta.xml
<CustomField>
    <fullName>UWM_Loan_Info_ID__c</fullName>
    <externalId>true</externalId>
    <label>UWM Loan Info ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Event__e/UWM_Event__e.object-meta.xml
<CustomObject>
    <label>UWM Event</label>
    <pluralLabel>UWM Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/UWM_Event__e/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Event__e/fields/UWM_Loan_Info_ID__c.field-meta.xml
<CustomField>
    <fullName>UWM_Loan_Info_ID__c</fullName>
    <label>UWM Loan Info ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Insights_Mapping__mdt/UWM_Insights_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>UWM Insights Mapping</label>
    <pluralLabel>UWM Insights Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/UWM_Insights_Mapping__mdt/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <label>API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Insights_Mapping__mdt/fields/Convert_Datetime_to_Date__c.field-meta.xml
<CustomField>
    <fullName>Convert_Datetime_to_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Convert Datetime to Date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UWM_Insights_Mapping__mdt/fields/Datatype__c.field-meta.xml
<CustomField>
    <fullName>Datatype__c</fullName>
    <label>Datatype</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boolean</fullName>
                <default>true</default>
                <label>Boolean</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UWM_Insights_Mapping__mdt/fields/Transaction_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Field_API_Name__c</fullName>
    <label>Transaction Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Loan_Info__c/UWM_Loan_Info__c.object-meta.xml
<CustomObject>
    <label>UWM Loan Info</label>
    <nameField>
        <label>UWM Loan Info</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UWM Loan Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UWM_Loan_Info__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>UWM Loan Infos</relationshipLabel>
    <relationshipName>UWM_Loan_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UWM_Loan_Info__c/fields/uwm_ClearToCloseDate__c.field-meta.xml
<CustomField>
    <fullName>uwm_ClearToCloseDate__c</fullName>
    <label>Clear To Close Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UWM_Translated_Value__mdt/UWM_Translated_Value__mdt.object-meta.xml
<CustomObject>
    <label>UWM Translated Value</label>
    <pluralLabel>UWM Translated Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/UWM_Translated_Value__mdt/fields/Input_Value__c.field-meta.xml
<CustomField>
    <fullName>Input_Value__c</fullName>
    <label>Input Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Translated_Value__mdt/fields/Output_Value__c.field-meta.xml
<CustomField>
    <fullName>Output_Value__c</fullName>
    <label>Output Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UWM_Translated_Value__mdt/fields/UWM_Insights_Mapping__c.field-meta.xml
<CustomField>
    <fullName>UWM_Insights_Mapping__c</fullName>
    <label>UWM Insights Mapping</label>
    <referenceTo>UWM_Insights_Mapping__mdt</referenceTo>
    <relationshipLabel>UWM Translated Values</relationshipLabel>
    <relationshipName>UWM_Translated_Values</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/UwmEventTriggerHandler.cls
public class UwmEventTriggerHandler {
    private static final String TRANSACTION_STATUS_FIELD = 'Status__c';
    private static final Set<String> SALESFORCE_MANAGED_STATUSES = new Set<String>{
        'Closing',
        'Funding',
        'PC Review',
        'Post-Closed'
    };

    public static void handleAfterInsert(List<UWM_Event__e> events, List<UWM_Insights_Mapping__mdt> metadata){
        List<SObject> transactionsToUpdate = new List<SObject>(); 
        Set<Id> processedTransactions = new Set<Id>();
        for(UWM_Event__e event : events){            
            UWM_Loan_Info__c info = UWMLoanInfoRepository.getInstance().getUWMLoanById(event.UWM_Loan_Info_ID__c); 
            Transaction__c transact = TransactionRepository.getInstance().getTransactionById(event.Transaction_ID__c); 
            SObject infoObject = (SObject)info;
            SObject transactionObject = (SObject) transact;
            for(UWM_Insights_Mapping__mdt mData : metadata){
                Object val;
                if(mData.Transaction_Field_API_Name__c != null && mData.API_Name__c != null){
                    System.debug(mData.API_Name__c + ' => ' + mData.Transaction_Field_API_Name__c);
                    
                    if(mData.UWM_Translated_Values__r == null || mData.UWM_Translated_Values__r.size() == 0){
                        if(mData.Datatype__c == 'Datetime' && mData.Convert_Datetime_to_Date__c == true){ 
                            Datetime datetimeValue = (Datetime)info.get(mData.API_Name__c);
                            if(datetimeValue != null){
                                System.debug('  Original DateTime: ' + datetimeValue);
                                //String formatDatetime = (Date.newInstance(datetimeValue.year(), datetimeValue.month(),datetimeValue.day())).format();

                                putMappedValue(transactionObject, transact, info, mData.Transaction_Field_API_Name__c, datetimeValue.dateGMT()); //Date.parse(formatDatetime));
                                 System.debug('  Formatted DateTime: ' + datetimeValue.dateGMT());
                            }else{                                                               
                                putMappedValue(transactionObject, transact, info, mData.Transaction_Field_API_Name__c, null);  
                            }
                        }else{ 
                            try {
                                putMappedValue(transactionObject, transact, info, mData.Transaction_Field_API_Name__c, infoObject.get(mData.API_Name__c)); 
                            } catch (Exception e) {
                                throw new UwmEventTriggerHandlerException('Error mapping fields ' + mData.Transaction_Field_API_Name__c + ', ' + mData.API_Name__c + '. Error ' + e.getMessage());
                            }
                            
                        }
                    }               
                    else{
                        for(UWM_Translated_Value__mdt translation : mData.UWM_Translated_Values__r){
                            if(infoObject.get(mData.API_Name__c) == translation.Input_Value__c){
                                val = translation.Output_Value__c; 
                            }
                        }
                        if(val != null || mData.Transaction_Field_API_Name__c == TRANSACTION_STATUS_FIELD){
                            putMappedValue(transactionObject, transact, info, mData.Transaction_Field_API_Name__c, val); 
                        }
                    }
                }
            }            
            
            if (!processedTransactions.contains(transactionObject.Id)) {
                transactionsToUpdate.add(transactionObject);
                processedTransactions.add(transactionObject.Id);
            }

            //transactionsToUpdate.add(transactionObject);             
        }        
        if(transactionsToUpdate.size() > 0){
            update transactionsToUpdate;
        } 
    }
    
    private static void putMappedValue(SObject transactionObject, Transaction__c originalTransaction, UWM_Loan_Info__c info, String fieldApiName, Object mappedValue){
        mappedValue = getDerivedMappedValue(originalTransaction, info, fieldApiName, mappedValue);
        if(!shouldApplyMappedValue(originalTransaction, fieldApiName, mappedValue)){
            return;
        }

        transactionObject.put(fieldApiName, mappedValue);
    }

    private static Object getDerivedMappedValue(Transaction__c originalTransaction, UWM_Loan_Info__c info, String fieldApiName, Object mappedValue){
        if(fieldApiName != TRANSACTION_STATUS_FIELD || originalTransaction == null || info == null){
            return mappedValue;
        }

        if(SALESFORCE_MANAGED_STATUSES.contains(originalTransaction.Status__c)){
            return mappedValue;
        }

        if(String.valueOf(mappedValue) == 'Closing'){
            return 'Closing';
        }

        if(info.uwm_ClearToCloseDate__c != null){
            return 'Approved';
        }

        return mappedValue;
    }

    private static Boolean shouldApplyMappedValue(Transaction__c originalTransaction, String fieldApiName, Object mappedValue){
        if(fieldApiName != TRANSACTION_STATUS_FIELD){
            return true;
        }

        String currentStatus = originalTransaction.Status__c;
        if(SALESFORCE_MANAGED_STATUSES.contains(currentStatus)){
            return false;
        }

        if(mappedValue == null){
            return false;
        }

        String incomingStatus = String.valueOf(mappedValue);
        if(incomingStatus == 'Closing'){
            return true;
        }

        return !SALESFORCE_MANAGED_STATUSES.contains(incomingStatus);
    }

    public class UwmEventTriggerHandlerException extends Exception {}
}