force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Account Name)</relationshipLabel>
    <relationshipName>Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/First_Mortgage__c.field-meta.xml
<CustomField>
    <fullName>First_Mortgage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Mortgage</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions (DPA)</relationshipLabel>
    <relationshipName>Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lender_lookup__c.field-meta.xml
<CustomField>
    <fullName>Lender_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Investor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Lender)</relationshipLabel>
    <relationshipName>Transactions_Lender</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lien_Position__c.field-meta.xml
<CustomField>
    <fullName>Lien_Position__c</fullName>
    <label>Lien Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_1st__c</fullName>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_2nd__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_2nd__c</fullName>
    <label>Loan Amount (2nd)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Program_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_1st__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional Fixed</fullName>
            </value>
            <value>
                <fullName>Conventional ARM</fullName>
            </value>
            <value>
                <fullName>HomeReady / Home Possible</fullName>
            </value>
            <value>
                <fullName>High Balance Conventional</fullName>
            </value>
            <value>
                <fullName>Jumbo Fixed</fullName>
            </value>
            <value>
                <fullName>Jumbo ARM</fullName>
            </value>
            <value>
                <fullName>FHA Standard</fullName>
            </value>
            <value>
                <fullName>FHA Streamline</fullName>
            </value>
            <value>
                <fullName>FHA 203(b)</fullName>
            </value>
            <value>
                <fullName>FHA 203(k) Full</fullName>
            </value>
            <value>
                <fullName>FHA 203(k) Streamline</fullName>
            </value>
            <value>
                <fullName>VA Purchase</fullName>
            </value>
            <value>
                <fullName>VA IRRRL</fullName>
            </value>
            <value>
                <fullName>USDA Guaranteed</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>DSCR</fullName>
            </value>
            <value>
                <fullName>Asset Depletion</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Foreign National</fullName>
            </value>
            <value>
                <fullName>ITIN</fullName>
            </value>
            <value>
                <fullName>Community Mortgage</fullName>
            </value>
            <value>
                <fullName>Rate &amp; Term Refi</fullName>
            </value>
            <value>
                <fullName>Cash-Out Refi</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>Closed-End Second</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Type_1st_TD__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type_1st_TD__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional</fullName>
                <label>CONV</label>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>Jumbo</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>NonQM</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>DPA 2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>Property City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Postal_Code__c</fullName>
    <label>Property Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>Property State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rate_1st_TD__c.field-meta.xml
<CustomField>
    <fullName>Rate_1st_TD__c</fullName>
    <label>Rate</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/DpaSecondTransactionInvocableTest.cls
@IsTest
private class DpaSecondTransactionInvocableTest {
    private static Id getPersonAccountRecordTypeId() {
        List<RecordType> personAccountRecordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName = 'PersonAccount'
            LIMIT 1
        ];
        return personAccountRecordTypes.isEmpty() ? null : personAccountRecordTypes[0].Id;
    }

    @TestSetup
    static void setup() {
        Account borrower = new Account(LastName = 'Borrower');
        Id personAccountRecordTypeId = getPersonAccountRecordTypeId();
        if (personAccountRecordTypeId != null) {
            borrower.RecordTypeId = personAccountRecordTypeId;
        }
        insert borrower;

        Account lender = new Account(Name = 'Test Lender', Type = 'Investor');
        insert lender;

        Transaction__c t1 = new Transaction__c(
            Borrower_Name__c = borrower.Id,
            Account__c = borrower.Id,
            Lien_Position__c = '1st',
            Lender_lookup__c = lender.Id,
            Loan_Amount_1st__c = 100000,
            Loan_Type_1st_TD__c = 'Conventional',
            Loan_Program_1st__c = '30 yr Fixed',
            Rate_1st_TD__c = 5.0,
            Property_Address__c = '123 Main St',
            Property_City__c = 'City',
            Property_State__c = 'CA',
            Property_Postal_Code__c = '90210'
        );
        insert t1;
    }

    @IsTest
    static void testCreateSecondTransactions() {
        Transaction__c t1 = [SELECT Id FROM Transaction__c WHERE Lien_Position__c = '1st' LIMIT 1];
        
        DpaSecondTransactionInvocable.Request request = new DpaSecondTransactionInvocable.Request();
        request.parentTransactionId = String.valueOf(t1.Id);
        request.mode = 'AUTO';
        
        Test.startTest();
        List<DpaSecondTransactionInvocable.Result> results = DpaSecondTransactionInvocable.createSecondTransactions(new List<DpaSecondTransactionInvocable.Request>{request});
        Test.stopTest();
        
        System.assertEquals(1, results.size(), 'Should return 1 result');
        System.assertEquals(true, results[0].success, 'Should be successful');
        System.assertNotEquals(null, results[0].secondTransactionId, 'Should have created a second transaction');
        System.assertEquals('Borrower - ', results[0].secondTransactionName, 'Should return the formatted second transaction name');
        
        Transaction__c t2 = [SELECT Id, First_Mortgage__c FROM Transaction__c WHERE Id = :results[0].secondTransactionId];
        System.assertEquals(t1.Id, t2.First_Mortgage__c, 'Second transaction should be linked to first');
    }

    @IsTest
    static void testCreateSecondTransactionsManual() {
        Transaction__c t1 = [SELECT Id FROM Transaction__c WHERE Lien_Position__c = '1st' LIMIT 1];
        
        DpaSecondTransactionInvocable.Request request = new DpaSecondTransactionInvocable.Request();
        request.parentTransactionId = String.valueOf(t1.Id);
        request.mode = 'MANUAL';
        request.loanAmount2nd = 20000;
        request.rate2nd = 5.0;
        request.loanType2nd = 'Conventional';
        request.loanProgram2nd = 'DPA';
        
        Test.startTest();
        List<DpaSecondTransactionInvocable.Result> results = DpaSecondTransactionInvocable.createSecondTransactions(new List<DpaSecondTransactionInvocable.Request>{request});
        Test.stopTest();
        
        System.assertEquals(1, results.size(), 'Should return 1 result');
        System.assertEquals(true, results[0].success, 'Should be successful');
        System.assertNotEquals(null, results[0].secondTransactionId, 'Should have created a second transaction');
        System.assertEquals('Borrower - ', results[0].secondTransactionName, 'Should return the formatted second transaction name');
        
        Transaction__c t2 = [SELECT Id, First_Mortgage__c, Loan_Amount_2nd__c FROM Transaction__c WHERE Id = :results[0].secondTransactionId];
        System.assertEquals(t1.Id, t2.First_Mortgage__c, 'Second transaction should be linked to first');
        System.assertEquals(20000, t2.Loan_Amount_2nd__c, 'Loan amount should match manual input');
    }

    @IsTest
    static void testCreateSecondTransactionsFail() {
        // Create a request with missing required fields for manual creation which defaults to null for auto fallback if fields are missing on parent
        // But here we'll use an invalid ID to force failure
        
        DpaSecondTransactionInvocable.Request request = new DpaSecondTransactionInvocable.Request();
        request.parentTransactionId = null; // Invalid ID
        
        Test.startTest();
        List<DpaSecondTransactionInvocable.Result> results = DpaSecondTransactionInvocable.createSecondTransactions(new List<DpaSecondTransactionInvocable.Request>{request});
        Test.stopTest();
        
        System.assertEquals(1, results.size(), 'Should return 1 result');
        System.assertEquals(false, results[0].success, 'Should fail');
        System.assertNotEquals(null, results[0].errorCode, 'Should have error code');
    }

    @IsTest
    static void testCreateSecondTransactionsInvalidParentIdString() {
        DpaSecondTransactionInvocable.Request request = new DpaSecondTransactionInvocable.Request();
        request.parentTransactionId = 'not-an-id';

        Test.startTest();
        List<DpaSecondTransactionInvocable.Result> results =
            DpaSecondTransactionInvocable.createSecondTransactions(
                new List<DpaSecondTransactionInvocable.Request>{ request }
            );
        Test.stopTest();

        System.assertEquals(1, results.size(), 'Should return 1 result');
        System.assertEquals(false, results[0].success, 'Should fail gracefully for invalid string IDs');
        System.assertEquals('INVALID_INPUT', results[0].errorCode, 'Invalid string IDs should be treated as invalid input');
    }
}