force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/BPS__c.field-meta.xml
<CustomField>
    <fullName>BPS__c</fullName>
    <label>BPS</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Clear_to_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Clear_to_Close_Date__c</fullName>
    <label>Clear to Close Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Closing_Package_One_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Closing_Package_One_Drive_Link__c</fullName>
    <label>Closing Package One Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Closing_Package_Sent__c.field-meta.xml
<CustomField>
    <fullName>Closing_Package_Sent__c</fullName>
    <label>Closing Package Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <description>Lead source, mapped from lead object</description>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reach In Market Dialer</fullName>
            </value>
            <value>
                <fullName>Realtor Referral</fullName>
            </value>
            <value>
                <fullName>Past Client</fullName>
            </value>
            <value>
                <fullName>Personal Referral</fullName>
            </value>
            <value>
                <fullName>Nickley Listing Credit</fullName>
            </value>
            <value>
                <fullName>Previous Client Referral</fullName>
            </value>
            <value>
                <fullName>Google_Organic</fullName>
                <label>Google Organic</label>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Zillow</fullName>
            </value>
            <value>
                <fullName>Nickley ISA</fullName>
            </value>
            <value>
                <fullName>Tik Tok</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>VM Refinance</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Facebook - Landing Refi</fullName>
            </value>
            <value>
                <fullName>Facebook Text Quote</fullName>
            </value>
            <value>
                <fullName>Facebook Lead Ad</fullName>
            </value>
            <value>
                <fullName>Consumer Webinar</fullName>
            </value>
            <value>
                <fullName>Instagram-Linktree</fullName>
            </value>
            <value>
                <fullName>Facebook-Linktree</fullName>
            </value>
            <value>
                <fullName>Youtube-Linktree</fullName>
            </value>
            <value>
                <fullName>Tiktok-Linktree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_1st__c</fullName>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EmailMessageTriggerHandlerTest.cls
@IsTest
private class EmailMessageTriggerHandlerTest {
    @testSetup static void setup() {
        Account acc = (Account)TDF.createSObject('Account', new Map<String,Object>{
                'FirstName' => 'Test',
                'LastName' => 'Somebody',
                'PersonEmail' => 'test@email.com',
                'RecordTypeId' => [SELECT Id, Name FROM RecordType WHERE Name = 'Person Account'].Id
        });

        Transaction__c o = new Transaction__c(Borrower_Name__c=acc.Id,Name='TodaysTest',Clear_to_Close_Date__c=date.today().addMonths(1), BPS__c=0.10, Loan_Amount_1st__c=250000,Lead_Source__c='Website - Purchase');
        insert o;

    }

    @IsTest
    static void testForDateStamp() {
        Transaction__c transact = [SELECT Id FROM Transaction__c LIMIT 1];
        transact.Closing_Package_One_Drive_Link__c = 'abc';
        update transact;
        
        EmailTemplate temp = [Select id from EmailTemplate where DeveloperName = 'Closing_Instructions_Funding_Authorization_1656379782794'];

        EmailMessage emailMessage = new EmailMessage();
        emailMessage.status = '3'; // email was sent
        emailMessage.relatedToId = transact.Id;
        emailMessage.fromAddress = 'test@test.com'; // from address
        emailMessage.fromName = 'Test Department'; // from name
        emailMessage.toAddress = 'test@example.com';
        emailMessage.Subject = 'Hello';
        emailMessage.EmailTemplateId = temp.Id;
        emailMessage.HtmlBody = 'Hello World';

        insert emailMessage;
        Transaction__c o = [SELECT Id, Closing_Package_Sent__c FROM  Transaction__c WHERE Name = 'TodaysTest'];
    }
    

    @IsTest
    static void testForNoLink() {
        Transaction__c transact = [SELECT Id, Closing_Package_Sent__c FROM  Transaction__c WHERE Name = 'TodaysTest'];        
        EmailTemplate temp = [Select id from EmailTemplate where DeveloperName = 'Closing_Instructions_Funding_Authorization_1656379782794'];

        EmailMessage emailMessage = new EmailMessage();
        emailMessage.status = '3'; // email was sent
        emailMessage.relatedToId = transact.Id;
        emailMessage.fromAddress = 'test@test.com'; // from address
        emailMessage.fromName = 'Test Department'; // from name
        emailMessage.toAddress = 'test@example.com';
        emailMessage.Subject = 'Hello';
        emailMessage.EmailTemplateId = temp.Id;
        emailMessage.HtmlBody = 'Hello World';
		
        Boolean isExceptionCaught = false;
        try{            
            insert emailMessage;
        }catch(DmlException e){
            isExceptionCaught = true;
        }
        System.assertEquals(true,isExceptionCaught);
    }
}