force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Account Name)</relationshipLabel>
    <relationshipName>Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Appraisal__c.field-meta.xml
<CustomField>
    <fullName>Appraisal__c</fullName>
    <label>Appraisal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needed</fullName>
            </value>
            <value>
                <fullName>PIW</fullName>
            </value>
            <value>
                <fullName>ACE + PDR/PDI</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Appraised_Value__c.field-meta.xml
<CustomField>
    <fullName>Appraised_Value__c</fullName>
    <label>Appraised Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Disclosures_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Disclosures_Out_Date__c</fullName>
    <label>Disclosures Out Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Disclosures_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Disclosures_Received_Date__c</fullName>
    <label>Disclosures Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/First_Mortgage__c.field-meta.xml
<CustomField>
    <fullName>First_Mortgage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Mortgage</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions (DPA)</relationshipLabel>
    <relationshipName>Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lender_lookup__c.field-meta.xml
<CustomField>
    <fullName>Lender_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Investor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Lender)</relationshipLabel>
    <relationshipName>Transactions_Lender</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lien_Position__c.field-meta.xml
<CustomField>
    <fullName>Lien_Position__c</fullName>
    <label>Lien Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_1st__c</fullName>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_2nd__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_2nd__c</fullName>
    <label>Loan Amount (2nd)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Program_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Program_1st__c</fullName>
    <label>Loan Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional Fixed</fullName>
            </value>
            <value>
                <fullName>Conventional ARM</fullName>
            </value>
            <value>
                <fullName>HomeReady / Home Possible</fullName>
            </value>
            <value>
                <fullName>High Balance Conventional</fullName>
            </value>
            <value>
                <fullName>Jumbo Fixed</fullName>
            </value>
            <value>
                <fullName>Jumbo ARM</fullName>
            </value>
            <value>
                <fullName>FHA Standard</fullName>
            </value>
            <value>
                <fullName>FHA Streamline</fullName>
            </value>
            <value>
                <fullName>FHA 203(b)</fullName>
            </value>
            <value>
                <fullName>FHA 203(k) Full</fullName>
            </value>
            <value>
                <fullName>FHA 203(k) Streamline</fullName>
            </value>
            <value>
                <fullName>VA Purchase</fullName>
            </value>
            <value>
                <fullName>VA IRRRL</fullName>
            </value>
            <value>
                <fullName>USDA Guaranteed</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>DSCR</fullName>
            </value>
            <value>
                <fullName>Asset Depletion</fullName>
            </value>
            <value>
                <fullName>Interest Only</fullName>
            </value>
            <value>
                <fullName>Foreign National</fullName>
            </value>
            <value>
                <fullName>ITIN</fullName>
            </value>
            <value>
                <fullName>Community Mortgage</fullName>
            </value>
            <value>
                <fullName>Rate &amp; Term Refi</fullName>
            </value>
            <value>
                <fullName>Cash-Out Refi</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>Closed-End Second</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Type_1st_TD__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type_1st_TD__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional</fullName>
                <label>CONV</label>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>Jumbo</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>NonQM</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>DPA 2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Residence</fullName>
            </value>
            <value>
                <fullName>Second Home</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Investment - Rental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Processor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>Property City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Postal_Code__c</fullName>
    <label>Property Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>Property State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Town House</fullName>
            </value>
            <value>
                <fullName>1 Unit</fullName>
            </value>
            <value>
                <fullName>2-4 Units</fullName>
            </value>
            <value>
                <fullName>4-10 Units</fullName>
            </value>
            <value>
                <fullName>10+ Units</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Mobile Home</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <label>Property Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rate_1st_TD__c.field-meta.xml
<CustomField>
    <fullName>Rate_1st_TD__c</fullName>
    <label>Rate</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rate_Lock_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Rate_Lock_Exp_Date__c</fullName>
    <label>Rate Lock Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rate_Lock_Status__c.field-meta.xml
<CustomField>
    <fullName>Rate_Lock_Status__c</fullName>
    <label>Rate Lock Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Need Lock Requested</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TRID Application</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Submission Form Complete</label>
            </value>
            <value>
                <fullName>Disclosures Out</fullName>
            </value>
            <value>
                <fullName>Pre-Processing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Waiting On Loan Officer</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Re-Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PC Review</fullName>
            </value>
            <value>
                <fullName>Post-Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DpaSecondTransactionConnectionTest.cls
@IsTest
private class DpaSecondTransactionConnectionTest {
    private static Id getPersonAccountRecordTypeId() {
        List<RecordType> personAccountRecordTypes = [
            SELECT Id
            FROM RecordType
            WHERE SObjectType = 'Account'
            AND DeveloperName = 'PersonAccount'
            LIMIT 1
        ];
        return personAccountRecordTypes.isEmpty() ? null : personAccountRecordTypes[0].Id;
    }

    private static Account createBorrower(String suffix) {
        Account borrower = new Account(LastName = suffix);
        Id personAccountRecordTypeId = getPersonAccountRecordTypeId();
        if (personAccountRecordTypeId != null) {
            borrower.RecordTypeId = personAccountRecordTypeId;
        }
        insert borrower;
        return borrower;
    }

    private static Account createLender(String suffix) {
        Account lender = new Account(
            Name = 'Lender ' + suffix,
            Type = 'Investor'
        );
        insert lender;
        return lender;
    }

    private static Transaction__c createFirstTransaction(Account borrower, Account lender) {
        Transaction__c firstTransaction = new Transaction__c(
            Borrower_Name__c = borrower.Id,
            Account__c = borrower.Id,
            Status__c = 'Open',
            Lien_Position__c = '1st',
            Lender_lookup__c = lender.Id,
            Loan_Amount_1st__c = 150000,
            Loan_Type_1st_TD__c = 'Conventional',
            Loan_Program_1st__c = '30 yr Fixed',
            Rate_1st_TD__c = 5.125,
            Property_Address__c = '123 Main St',
            Property_City__c = 'Miami',
            Property_State__c = 'FL',
            Property_Postal_Code__c = '33101',
            Property_Unit__c = 'A',
            Property_Type__c = 'Single Family',
            Purchase_Date__c = Date.newInstance(2026, 5, 1),
            Appraisal__c = 'Needed',
            Appraised_Value__c = 250000,
            Purchase_Price__c = 245000,
            Processor__c = UserInfo.getUserId(),
            Closing_Date__c = Date.newInstance(2026, 6, 15),
            Funding_Date__c = Date.newInstance(2026, 6, 16),
            Disclosures_Out_Date__c = Datetime.newInstance(2026, 5, 2, 10, 0, 0),
            Disclosures_Received_Date__c = Datetime.newInstance(2026, 5, 3, 11, 0, 0),
            Rate_Lock_Status__c = 'Locked',
            Rate_Lock_Exp_Date__c = Date.newInstance(2026, 6, 30),
            Occupancy__c = 'Primary Residence'
        );
        insert firstTransaction;
        return firstTransaction;
    }

    @IsTest
    static void dpaSecondCopiesTransactionPageFieldsOnCreate() {
        Account borrower = createBorrower('Connection Copy');
        Account lender = createLender('Connection Copy');
        Transaction__c firstTransaction = createFirstTransaction(borrower, lender);

        DpaSecondTransactionService.Request requestItem = new DpaSecondTransactionService.Request();
        requestItem.firstTransactionId = firstTransaction.Id;
        requestItem.mode = DpaSecondTransactionService.MODE_AUTO;

        Test.startTest();
        List<DpaSecondTransactionService.Result> results =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{ requestItem });
        Test.stopTest();

        System.assertEquals(true, results[0].success);

        Transaction__c secondTransaction = [
            SELECT
                Status__c,
                First_Mortgage__c,
                Property_Address__c,
                Property_City__c,
                Property_State__c,
                Property_Postal_Code__c,
                Property_Unit__c,
                Property_Type__c,
                Purchase_Date__c,
                Appraisal__c,
                Appraised_Value__c,
                Purchase_Price__c,
                Processor__c,
                Closing_Date__c,
                Funding_Date__c,
                Disclosures_Out_Date__c,
                Disclosures_Received_Date__c,
                Rate_Lock_Status__c,
                Rate_Lock_Exp_Date__c,
                Occupancy__c,
                Lender_lookup__c,
                Loan_Amount_1st__c,
                Loan_Type_1st_TD__c,
                Loan_Program_1st__c,
                Rate_1st_TD__c,
                Loan_Amount_2nd__c,
                Loan_Type_2nd_TD__c,
                Loan_Program_2nd__c,
                Rate_2nd_TD__c
            FROM Transaction__c
            WHERE Id = :results[0].createdSecondTransactionId
        ];

        System.assertEquals(firstTransaction.Id, secondTransaction.First_Mortgage__c);
        System.assertEquals(firstTransaction.Property_Address__c, secondTransaction.Property_Address__c);
        System.assertEquals(firstTransaction.Property_City__c, secondTransaction.Property_City__c);
        System.assertEquals(firstTransaction.Property_State__c, secondTransaction.Property_State__c);
        System.assertEquals(firstTransaction.Property_Postal_Code__c, secondTransaction.Property_Postal_Code__c);
        System.assertEquals(firstTransaction.Property_Unit__c, secondTransaction.Property_Unit__c);
        System.assertEquals(firstTransaction.Property_Type__c, secondTransaction.Property_Type__c);
        System.assertEquals(firstTransaction.Purchase_Date__c, secondTransaction.Purchase_Date__c);
        System.assertEquals(firstTransaction.Appraisal__c, secondTransaction.Appraisal__c);
        System.assertEquals(firstTransaction.Appraised_Value__c, secondTransaction.Appraised_Value__c);
        System.assertEquals(firstTransaction.Purchase_Price__c, secondTransaction.Purchase_Price__c);
        System.assertEquals(firstTransaction.Processor__c, secondTransaction.Processor__c);
        System.assertEquals(firstTransaction.Closing_Date__c, secondTransaction.Closing_Date__c);
        System.assertEquals(firstTransaction.Funding_Date__c, secondTransaction.Funding_Date__c);
        System.assertEquals(firstTransaction.Disclosures_Out_Date__c, secondTransaction.Disclosures_Out_Date__c);
        System.assertEquals(firstTransaction.Disclosures_Received_Date__c, secondTransaction.Disclosures_Received_Date__c);
        System.assertEquals(firstTransaction.Rate_Lock_Status__c, secondTransaction.Rate_Lock_Status__c);
        System.assertEquals(firstTransaction.Rate_Lock_Exp_Date__c, secondTransaction.Rate_Lock_Exp_Date__c);
        System.assertEquals(firstTransaction.Occupancy__c, secondTransaction.Occupancy__c);
        System.assertEquals(lender.Id, secondTransaction.Lender_lookup__c);
        System.assertEquals(150000, secondTransaction.Loan_Amount_1st__c);
        System.assertEquals('Conventional', secondTransaction.Loan_Type_1st_TD__c);
        System.assertEquals('30 yr Fixed', secondTransaction.Loan_Program_1st__c);
        System.assertEquals(5.125, secondTransaction.Rate_1st_TD__c);
        System.assertEquals(150000, secondTransaction.Loan_Amount_2nd__c);
        System.assertEquals('Conventional', secondTransaction.Loan_Type_2nd_TD__c);
        System.assertEquals('30 yr Fixed', secondTransaction.Loan_Program_2nd__c);
        System.assertEquals(5.125, secondTransaction.Rate_2nd_TD__c);
    }

    @IsTest
    static void submissionFormValuesOverridePrimaryLoanInfoWithoutManualMode() {
        Account borrower = createBorrower('Connection Override');
        Account firstLender = createLender('Connection Override First');
        Account secondLender = createLender('Connection Override Second');
        Transaction__c firstTransaction = createFirstTransaction(borrower, firstLender);

        DpaSecondTransactionService.Request requestItem = new DpaSecondTransactionService.Request();
        requestItem.firstTransactionId = firstTransaction.Id;
        requestItem.lenderId = secondLender.Id;
        requestItem.loanAmount2nd = 10000;
        requestItem.loanType2nd = 'DPA 2nd';
        requestItem.loanProgram2nd = 'Closed-End Second';
        requestItem.rate2nd = 0;

        Test.startTest();
        List<DpaSecondTransactionService.Result> results =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{ requestItem });
        Test.stopTest();

        System.assertEquals(true, results[0].success);

        Transaction__c secondTransaction = [
            SELECT
                First_Mortgage__c,
                Lender_lookup__c,
                Loan_Amount_1st__c,
                Loan_Type_1st_TD__c,
                Loan_Program_1st__c,
                Rate_1st_TD__c,
                Loan_Amount_2nd__c,
                Loan_Type_2nd_TD__c,
                Loan_Program_2nd__c,
                Rate_2nd_TD__c
            FROM Transaction__c
            WHERE Id = :results[0].createdSecondTransactionId
        ];

        System.assertEquals(firstTransaction.Id, secondTransaction.First_Mortgage__c);
        System.assertEquals(secondLender.Id, secondTransaction.Lender_lookup__c);
        System.assertEquals(10000, secondTransaction.Loan_Amount_1st__c);
        System.assertEquals('DPA 2nd', secondTransaction.Loan_Type_1st_TD__c);
        System.assertEquals('Closed-End Second', secondTransaction.Loan_Program_1st__c);
        System.assertEquals(0, secondTransaction.Rate_1st_TD__c);
        System.assertEquals(10000, secondTransaction.Loan_Amount_2nd__c);
        System.assertEquals('DPA 2nd', secondTransaction.Loan_Type_2nd_TD__c);
        System.assertEquals('Closed-End Second', secondTransaction.Loan_Program_2nd__c);
        System.assertEquals(0, secondTransaction.Rate_2nd_TD__c);
    }

    @IsTest
    static void primaryStatusChangeMovesLinkedSecondStatus() {
        Account borrower = createBorrower('Connection Status');
        Account lender = createLender('Connection Status');
        Transaction__c firstTransaction = createFirstTransaction(borrower, lender);

        DpaSecondTransactionService.Request requestItem = new DpaSecondTransactionService.Request();
        requestItem.firstTransactionId = firstTransaction.Id;
        requestItem.mode = DpaSecondTransactionService.MODE_AUTO;
        List<DpaSecondTransactionService.Result> results =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{ requestItem });

        Test.startTest();
        update new Transaction__c(
            Id = firstTransaction.Id,
            Status__c = 'Processing',
            Purchase_Price__c = 255000,
            Appraised_Value__c = 260000,
            Closing_Date__c = Date.newInstance(2026, 7, 15),
            Rate_Lock_Status__c = 'Floating',
            Occupancy__c = 'Second Home'
        );
        Test.stopTest();

        Transaction__c secondTransaction = [
            SELECT
                Status__c,
                Purchase_Price__c,
                Appraised_Value__c,
                Closing_Date__c,
                Rate_Lock_Status__c,
                Occupancy__c
            FROM Transaction__c
            WHERE Id = :results[0].createdSecondTransactionId
        ];
        System.assertEquals('Processing', secondTransaction.Status__c);
        System.assertEquals(255000, secondTransaction.Purchase_Price__c);
        System.assertEquals(260000, secondTransaction.Appraised_Value__c);
        System.assertEquals(Date.newInstance(2026, 7, 15), secondTransaction.Closing_Date__c);
        System.assertEquals('Floating', secondTransaction.Rate_Lock_Status__c);
        System.assertEquals('Second Home', secondTransaction.Occupancy__c);
    }

    @IsTest
    static void secondStatusChangeDoesNotMovePrimaryStatusBackwards() {
        Account borrower = createBorrower('Connection One Way');
        Account lender = createLender('Connection One Way');
        Transaction__c firstTransaction = createFirstTransaction(borrower, lender);

        DpaSecondTransactionService.Request requestItem = new DpaSecondTransactionService.Request();
        requestItem.firstTransactionId = firstTransaction.Id;
        requestItem.mode = DpaSecondTransactionService.MODE_AUTO;
        List<DpaSecondTransactionService.Result> results =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{ requestItem });
        Transaction__c statusBeforeSecondUpdate = [
            SELECT Status__c
            FROM Transaction__c
            WHERE Id = :firstTransaction.Id
        ];

        Test.startTest();
        update new Transaction__c(
            Id = results[0].createdSecondTransactionId,
            Status__c = 'Processing'
        );
        Test.stopTest();

        Transaction__c reloadedFirst = [
            SELECT Status__c
            FROM Transaction__c
            WHERE Id = :firstTransaction.Id
        ];
        System.assertEquals(statusBeforeSecondUpdate.Status__c, reloadedFirst.Status__c);
    }

    @IsTest
    static void createSecondTransactionsHandlesGuardrails() {
        Account borrower = createBorrower('Connection Guardrails');
        Account lender = createLender('Connection Guardrails');
        Transaction__c firstTransaction = createFirstTransaction(borrower, lender);

        DpaSecondTransactionService.Request missingIdRequest = new DpaSecondTransactionService.Request();

        DpaSecondTransactionService.Request missingInfoRequest = new DpaSecondTransactionService.Request();
        missingInfoRequest.firstTransactionId = firstTransaction.Id;
        missingInfoRequest.lenderId = null;
        missingInfoRequest.loanAmount2nd = null;
        missingInfoRequest.loanType2nd = '';
        missingInfoRequest.loanProgram2nd = '';
        missingInfoRequest.rate2nd = null;

        Test.startTest();
        List<DpaSecondTransactionService.Result> missingResults =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{
                null,
                missingIdRequest
            });
        Test.stopTest();

        System.assertEquals(2, missingResults.size());
        System.assertEquals(false, missingResults[0].success);
        System.assertEquals('INVALID_INPUT', missingResults[0].errorCode);
        System.assertEquals(false, missingResults[1].success);
        System.assertEquals('INVALID_INPUT', missingResults[1].errorCode);

        Transaction__c secondLikeTransaction = new Transaction__c(
            Borrower_Name__c = borrower.Id,
            Account__c = borrower.Id,
            Status__c = 'Processing',
            Lien_Position__c = '2nd',
            Lender_lookup__c = lender.Id,
            Loan_Amount_1st__c = 150000,
            Loan_Type_1st_TD__c = 'Conventional',
            Loan_Program_1st__c = '30 yr Fixed',
            Rate_1st_TD__c = 5.125
        );
        insert secondLikeTransaction;

        DpaSecondTransactionService.Request invalidFirstRequest = new DpaSecondTransactionService.Request();
        invalidFirstRequest.firstTransactionId = secondLikeTransaction.Id;

        List<DpaSecondTransactionService.Result> invalidResults =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{
                invalidFirstRequest
            });

        System.assertEquals(false, invalidResults[0].success);
        System.assertEquals('INVALID_FIRST_TRANSACTION', invalidResults[0].errorCode);

        DpaSecondTransactionService.Request validRequest = new DpaSecondTransactionService.Request();
        validRequest.firstTransactionId = firstTransaction.Id;
        List<DpaSecondTransactionService.Result> validResults =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{
                validRequest
            });
        System.assertEquals(true, validResults[0].success);

        DpaSecondTransactionService.Request duplicateRequest = new DpaSecondTransactionService.Request();
        duplicateRequest.firstTransactionId = firstTransaction.Id;
        List<DpaSecondTransactionService.Result> duplicateResults =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{
                duplicateRequest
            });

        System.assertEquals(false, duplicateResults[0].success);
        System.assertEquals('SECOND_ALREADY_EXISTS', duplicateResults[0].errorCode);

        Transaction__c incompleteFirstTransaction = createFirstTransaction(borrower, lender);
        update new Transaction__c(
            Id = incompleteFirstTransaction.Id,
            Lender_lookup__c = null,
            Loan_Amount_1st__c = null,
            Loan_Type_1st_TD__c = null,
            Loan_Program_1st__c = null,
            Rate_1st_TD__c = null
        );

        DpaSecondTransactionService.Request incompleteRequest = new DpaSecondTransactionService.Request();
        incompleteRequest.firstTransactionId = incompleteFirstTransaction.Id;
        List<DpaSecondTransactionService.Result> incompleteResults =
            DpaSecondTransactionService.createSecondTransactions(new List<DpaSecondTransactionService.Request>{
                incompleteRequest
            });

        System.assertEquals(false, incompleteResults[0].success);
        System.assertEquals('MISSING_REQUIRED_FIELDS', incompleteResults[0].errorCode);
    }
}