force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TRID Application</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Submission Form Complete</label>
            </value>
            <value>
                <fullName>Disclosures Out</fullName>
            </value>
            <value>
                <fullName>Pre-Processing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Waiting On Loan Officer</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Re-Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PC Review</fullName>
            </value>
            <value>
                <fullName>Post-Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransactionControllerTest.cls
@isTest 
private class TransactionControllerTest {

	@TestSetup
	static void testSetup(){
		Account a = new Account(PersonLeadSource='Website - Refi',LastName='test');
		insert a;
		Transaction__c t = new Transaction__c(Status__c='TRID Application',Borrower_Name__c=a.Id);
		insert t;
		
	}

	@isTest
	private static void testCloneTransaction() {
		Transaction__c t = [SELECT Id FROM Transaction__c LIMIT 1];
		String clonedId = TransactionController.clone('Transaction',t.Id);
		List<Transaction__c> transactions = [SELECT Id FROM Transaction__c];
		System.assertEquals(2,transactions.size());
	}
}