force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ClosingPortalControllerTests.cls
@IsTest
public class ClosingPortalControllerTests {
    
    @IsTest public static void test() {
        // Set up test data
        Account acc = new Account(Name = 'Test Borrower');
        insert acc;
        
        Transaction__c txn = new Transaction__c(
            Name = 'Test Transaction',
            Borrower_Name__c = acc.Id
        );
        insert txn;
        
        Test.startTest();
        ClosingPortalController.getTransactionStatus(txn.Id);
        ClosingPortalController.updateTransactionStatus(txn.Id, 'Rejected', 'Test Rejection Note');
        ClosingPortalController.sendEmail(txn.Id, new List<String> { 'Test File Name #1' });
        Test.stopTest();
    }
    
}