force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Account Name)</relationshipLabel>
    <relationshipName>Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Appraisal__c.field-meta.xml
<CustomField>
    <fullName>Appraisal__c</fullName>
    <label>Appraisal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Needed</fullName>
            </value>
            <value>
                <fullName>PIW</fullName>
            </value>
            <value>
                <fullName>ACE + PDR/PDI</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Appraised_Value__c.field-meta.xml
<CustomField>
    <fullName>Appraised_Value__c</fullName>
    <label>Appraised Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrower_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Last_Name__c</fullName>
    <label>Borrower Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Closing_Date__c</fullName>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Disclosures_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Disclosures_Out_Date__c</fullName>
    <label>Disclosures Out Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Disclosures_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Disclosures_Received_Date__c</fullName>
    <label>Disclosures Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/First_Mortgage__c.field-meta.xml
<CustomField>
    <fullName>First_Mortgage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First Mortgage</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions (DPA)</relationshipLabel>
    <relationshipName>Transactions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lender_lookup__c.field-meta.xml
<CustomField>
    <fullName>Lender_lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Investor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Lender)</relationshipLabel>
    <relationshipName>Transactions_Lender</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Lien_Position__c.field-meta.xml
<CustomField>
    <fullName>Lien_Position__c</fullName>
    <label>Lien Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount_1st__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount_1st__c</fullName>
    <label>Total Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Type_1st_TD__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type_1st_TD__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional</fullName>
                <label>CONV</label>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>Jumbo</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>NonQM</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>DPA 2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Occupancy__c</fullName>
    <label>Occupancy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Residence</fullName>
            </value>
            <value>
                <fullName>Second Home</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Investment - Rental</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Processor__c.field-meta.xml
<CustomField>
    <fullName>Processor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Processor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>Property City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Postal_Code__c</fullName>
    <label>Property Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>Property State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Town House</fullName>
            </value>
            <value>
                <fullName>1 Unit</fullName>
            </value>
            <value>
                <fullName>2-4 Units</fullName>
            </value>
            <value>
                <fullName>4-10 Units</fullName>
            </value>
            <value>
                <fullName>10+ Units</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Mobile Home</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Unit__c.field-meta.xml
<CustomField>
    <fullName>Property_Unit__c</fullName>
    <label>Property Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <label>Contract Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rate_Lock_Exp_Date__c.field-meta.xml
<CustomField>
    <fullName>Rate_Lock_Exp_Date__c</fullName>
    <label>Rate Lock Exp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Rate_Lock_Status__c.field-meta.xml
<CustomField>
    <fullName>Rate_Lock_Status__c</fullName>
    <label>Rate Lock Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Locked</fullName>
            </value>
            <value>
                <fullName>Need Lock Requested</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Second_Mortgage__c.field-meta.xml
<CustomField>
    <fullName>Second_Mortgage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Second Mortgage</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transactions (Second Mortgage)</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TRID Application</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Submission Form Complete</label>
            </value>
            <value>
                <fullName>Disclosures Out</fullName>
            </value>
            <value>
                <fullName>Pre-Processing</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Waiting On Loan Officer</fullName>
            </value>
            <value>
                <fullName>Conditionally Approved</fullName>
            </value>
            <value>
                <fullName>Re-Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>PC Review</fullName>
            </value>
            <value>
                <fullName>Post-Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Submission_Form_Date__c.field-meta.xml
<CustomField>
    <fullName>Submission_Form_Date__c</fullName>
    <label>Submission Form Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TransactionRepository.cls
/**
 * Created by toma on 5/19/2022.
 */

public with sharing class TransactionRepository {
    private static List<String> TRANSACTION_FIELDS;
    private static TransactionRepository self;
    static{
        List<String> fields = new List<String>();
        Set<String> relatedAccountFields = new Set<String>();
        Map<String, SObjectField> oppFieldMap = Schema.getGlobalDescribe().get('Transaction__c').getDescribe().fields.getMap();
        Map<String, SObjectField> accountFieldMap = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap();
        for(String fieldName : oppFieldMap.keySet())
        {
            fields.add(fieldName);
        }
        for(String fieldName : accountFieldMap.keySet()){
            relatedAccountFields.add('Borrower_Name__r.' + fieldName);
            
        }
        fields.addAll(relatedAccountFields); 
        TRANSACTION_FIELDS = fields;
    }
    public static TransactionRepository getInstance(){
        if(self==null){
            self = new TransactionRepository();
        }
        return self;
    }
    public Transaction__c getTransactionById(String id){
        System.debug('transaction record id: '+id);
        String query = 'SELECT ' + String.join(TRANSACTION_FIELDS, ',') + ' FROM Transaction__c WHERE Id=:id';
        System.debug('transaction query: '+query);
        Transaction__c loan = (Transaction__c)Database.query(query);
        return loan;
    }
    
    public Map<Id, Loan> getTransactionsMapByIds(Set<Id> loanIds) {
        String query = 'SELECT ' + String.join(TRANSACTION_FIELDS, ',')
            + ' FROM Transaction__c where Id IN: loanIds';
        
        Map<Id, Loan> loans = new Map<Id, Loan>();
        for (Transaction__c deal : (List<Transaction__c>) Database.query(query)) {
            loans.put(deal.Id, new Loan(deal));
        }
        return loans;
    }

    public Map<Id, Transaction__c> selectForDpaSecondByIds(Set<Id> transactionIds) {
        if (transactionIds == null || transactionIds.isEmpty()) {
            return new Map<Id, Transaction__c>();
        }

        return new Map<Id, Transaction__c>([
            SELECT
                Id,
                RecordTypeId,
                Status__c,
                Lien_Position__c,
                First_Mortgage__c,
                Second_Mortgage__c,
                Borrower_Name__c,
                Borrower_Name__r.LastName,
                Borrower_Last_Name__c,
                Account__c,
                Property_Address__c,
                Property_City__c,
                Property_State__c,
                Property_Postal_Code__c,
                Property_Unit__c,
                Property_Type__c,
                Purchase_Date__c,
                Appraisal__c,
                Appraised_Value__c,
                Purchase_Price__c,
                Processor__c,
                Closing_Date__c,
                Funding_Date__c,
                Disclosures_Out_Date__c,
                Disclosures_Received_Date__c,
                Rate_Lock_Status__c,
                Rate_Lock_Exp_Date__c,
                Occupancy__c,
                Submission_Form_Date__c,
                Lender_lookup__c,
                Loan_Amount_1st__c,
                Loan_Type_1st_TD__c,
                Loan_Program_1st__c,
                Rate_1st_TD__c
            FROM Transaction__c
            WHERE Id IN :transactionIds
        ]);
    }

    public Map<Id, Transaction__c> selectSecondTransactionsByFirstIds(Set<Id> firstTransactionIds) {
        Map<Id, Transaction__c> firstToSecond = new Map<Id, Transaction__c>();
        if (firstTransactionIds == null || firstTransactionIds.isEmpty()) {
            return firstToSecond;
        }

        for (Transaction__c secondTransaction : [
            SELECT Id, First_Mortgage__c
            FROM Transaction__c
            WHERE First_Mortgage__c IN :firstTransactionIds
        ]) {
            if (!firstToSecond.containsKey(secondTransaction.First_Mortgage__c)) {
                firstToSecond.put(secondTransaction.First_Mortgage__c, secondTransaction);
            }
        }

        return firstToSecond;
    }

    public Map<Id, Transaction__c> selectSecondTransactionNamesByIds(Set<Id> transactionIds) {
        if (transactionIds == null || transactionIds.isEmpty()) {
            return new Map<Id, Transaction__c>();
        }

        return new Map<Id, Transaction__c>([
            SELECT Id, Borrower_Name__r.LastName, Borrower_Last_Name__c, Loan_Number__c, Loan_2nd_TD__c
            FROM Transaction__c
            WHERE Id IN :transactionIds
        ]);
    }
    
    public List<Loan> getUWMLoans(){
        List<Transaction__c> transactions = new List<Transaction__c>();
        
        transactions = [
            SELECT Id, OwnerId, Loan_Number__c
            FROM Transaction__c
            WHERE Lender_lookup__r.Name = 'UWM' AND Loan_Number__c != NULL AND Closed__c = FALSE
        ];
        
        
        List<Loan> loans = new List<Loan>();
        for(Transaction__c deal : transactions){
            Loan openLoan = new Loan(deal);
            loans.add(openLoan);
        }
        return loans;
    }
}