force-app/main/default/objects/Transaction_Condition_Reference__c/Transaction_Condition_Reference__c.object-meta.xml
<CustomObject>
    <label>Transaction Condition Reference</label>
    <nameField>
        <displayFormat>TCR-{0000}</displayFormat>
        <label>Transaction Condition Reference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Condition References</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Borrower_Description__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Description__c</fullName>
    <label>Borrower Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Borrower_Label__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Label__c</fullName>
    <label>Borrower Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Employment_Type__c</fullName>
    <label>Employment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>W2</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional</fullName>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>HELOAN</fullName>
            </value>
            <value>
                <fullName>JUMBO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Self_Employment_Type__c.field-meta.xml
<CustomField>
    <fullName>Self_Employment_Type__c</fullName>
    <label>Self Employment Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>S Corporation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction_Condition_Reference__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan Officer</fullName>
            </value>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>Initial Submission</fullName>
            </value>
            <value>
                <fullName>Initial Submission Optional</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Vendor Standard</fullName>
            </value>
            <value>
                <fullName>Post Closing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferenceInvocableQuery.cls
/**
 * @author Andrei Karanko
 * @date 9/1/2023
 * description - This class is used to get the initial loan condition references
 * to create initial loan conditions. It is used in Conditions Creator flow
 */

global with sharing class ReferenceInvocableQuery {
    @InvocableMethod(Label='Get Initial Submission References')
    global static List<Response> getReferences(List<Request> requests){
        List<Response> responses = new List<Response>();

        Map<String, List<Transaction_Condition_Reference__c>> typeToConditionReferencesMap = getAllConditionReferencesWithAllTypesFromRequests(requests);
        if (typeToConditionReferencesMap.isEmpty()){
            return responses;
        }

        // loop through requests
        // for each request, get the list of condition references from the map
        for(Request req: requests){
            if(!typeToConditionReferencesMap.containsKey(req.type)){
                continue;
            }
            Response res = new Response();
            List<Transaction_Condition_Reference__c> conditionReferences = typeToConditionReferencesMap.get(req.type);
            List<Transaction_Condition_Reference__c> matchingConditionReferences = assessReferences(req, conditionReferences);
            if (!matchingConditionReferences.isEmpty()){
                res.conditions = matchingConditionReferences;
                responses.add(res);
            }
        }

        return responses;
    }

    private static Map<String, List<Transaction_Condition_Reference__c>> getAllConditionReferencesWithAllTypesFromRequests(List<Request> requests){
        // first get all the types from the requests
        Set<String> types = new Set<String>();
        for(Request req: requests){
            types.add(req.type);
        }

        // get all condition references that have all the types from the requests
        // this is to avoid having to query for each type in a loop
        List<Transaction_Condition_Reference__c> conditionsWithAllTypesFromRequest = [
            SELECT Id, Loan_Purpose__c, Employment_Type__c,Self_Employment_Type__c, Type__c, Borrower_Label__c, Borrower_Description__c, Loan_Type__c
            FROM Transaction_Condition_Reference__c
            WHERE Type__c IN :types
            WITH USER_MODE
        ];

        // loop through condition references with all types from request
        // to create a map with type as key and list of condition references as value
        Map<String, List<Transaction_Condition_Reference__c>> typeToConditionReferencesMap = new Map<String, List<Transaction_Condition_Reference__c>>();
        for(Transaction_Condition_Reference__c conditionReference: conditionsWithAllTypesFromRequest){
            if(!typeToConditionReferencesMap.containsKey(conditionReference.Type__c)){
                typeToConditionReferencesMap.put(conditionReference.Type__c, new List<Transaction_Condition_Reference__c>());
            }
            typeToConditionReferencesMap.get(conditionReference.Type__c).add(conditionReference);
        }
        return typeToConditionReferencesMap;
    }

    private static List<Transaction_Condition_Reference__c> assessReferences(Request req, List<Transaction_Condition_Reference__c> conditionReferences) {
        List<Transaction_Condition_Reference__c> matchingConditionReferences = new List<Transaction_Condition_Reference__c>();
        for(Transaction_Condition_Reference__c conditionReference: conditionReferences){
            if (isConditionMatch(req, conditionReference)) {
                matchingConditionReferences.add(conditionReference);
            }
        }
        return matchingConditionReferences;
    }

    private static Boolean isConditionMatch(Request req, Transaction_Condition_Reference__c conditionReference) {
        if (conditionReference.Loan_Purpose__c != null && !conditionReference.Loan_Purpose__c.contains(req.loanPurpose)) {
            return false;
        }
        if (conditionReference.Loan_Type__c != null && !conditionReference.Loan_Type__c.contains(req.loanType)) {
            return false;
        }
        if (req.employmentType != 'Self Employed') {
            if (conditionReference.Employment_Type__c != null && !conditionReference.Employment_Type__c.contains(req.employmentType)) {
                return false;
            }
        } else {
            if (conditionReference.Employment_Type__c != null && conditionReference.Employment_Type__c != 'Self Employed') {
                return false;
            }
            if (conditionReference.Self_Employment_Type__c != null && !conditionReference.Self_Employment_Type__c.contains(req.selfEmploymentType)) {
                return false;
            }
        }

        return true;
    }

    global class Response{
        @InvocableVariable
        global List<Transaction_Condition_Reference__c> conditions;
    }
    global class Request{
        @InvocableVariable
        global String loanType;
        @InvocableVariable
        global String loanPurpose;
        @InvocableVariable
        global String employmentType;
        @InvocableVariable
        global String selfEmploymentType;
        @InvocableVariable
        global String type;
    }
}