force-app/main/default/objects/Appraisal_Order__c/Appraisal_Order__c.object-meta.xml
<CustomObject>
    <label>Appraisal Order</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Appraisal Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisal Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal_Order__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Appraisal Orders</relationshipLabel>
    <relationshipName>Appraisal_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal_Order__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <label>Order ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ValueLink_AttachFIleWebservice.cls
@RestResource(UrlMapping='/valueLink/attachFile/v1')
global class ValueLink_AttachFIleWebservice {
    private static final String APPRAISAL_FOLDER = 'Appraisal';

	public class ValueLinkObj{
		public String orderId;
		public String fileName;
		public String data;
	}

	@HttpPost
	global static void doPost(){
		RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;
		try{
			String fileName = req.params.get('fileName');
			String orderId = req.params.get('orderId');
			System.debug('orderId =========== '+orderId);
			if(orderId != null){
				attachFileToTransaction(req.requestBody, fileName, orderId);
				res.responseBody = Blob.valueOf('File has been attached.');
				res.statusCode = 200;
			}else{
				res.responseBody = Blob.valueOf('Invalid OrderId.');
				res.statusCode = 400;
			}	

		}catch(Exception e){
			res.statusCode = 500;
            res.responseBody = Blob.valueOf('There was an error: ' + e.getMessage());
		}

	}
	@future
	public static void attachFileToTransaction(Blob payload,  String filename, String orderId){
		List<Appraisal_Order__c> appraisalOrders = [SELECT Id,Loan__c FROM Appraisal_Order__c WHERE Order_ID__c =: orderId];
		Blob fileData = EncodingUtil.base64Decode(payload.toString());
		if(appraisalOrders.size() == 1 && appraisalOrders[0].Loan__c != null){
			try{
				FilesRecipes.createFileAttachedToRecord(fileData, appraisalOrders[0].Loan__c, filename, APPRAISAL_FOLDER);
			}catch(Exception e){
				System.debug('Error Message '+e.getMessage());
				throw e;
			}
		}
	}
}