force-app/main/default/objects/Appraisal_Order__c/Appraisal_Order__c.object-meta.xml
<CustomObject>
    <label>Appraisal Order</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Appraisal Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisal Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Additional_Processor__c.field-meta.xml
<CustomField>
    <fullName>Additional_Processor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Processor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Appraisal_Order__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appraisal Order</label>
    <referenceTo>Appraisal_Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrower_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Last_Name__c</fullName>
    <label>Borrower Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrower_Name__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Borrower Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Borrowers_Phone__c.field-meta.xml
<CustomField>
    <fullName>Borrowers_Phone__c</fullName>
    <formula>Borrower_Name__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Borrowers Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Conditions_One_Drive_Link__c.field-meta.xml
<CustomField>
    <fullName>Conditions_One_Drive_Link__c</fullName>
    <label>Conditions One Drive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FedEx_Labels_Received__c.field-meta.xml
<CustomField>
    <fullName>FedEx_Labels_Received__c</fullName>
    <label>FedEx Labels Tendered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/FHA_Case_Number__c.field-meta.xml
<CustomField>
    <fullName>FHA_Case_Number__c</fullName>
    <label>FHA Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Number__c</fullName>
    <description>uwm repository query use for uwm insights</description>
    <label>Loan Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Loan_Purpose__c</fullName>
    <label>Loan Purpose</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchase</fullName>
            </value>
            <value>
                <fullName>Refinance</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>HELOAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Loan_Type_1st_TD__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type_1st_TD__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Conventional</fullName>
                <label>CONV</label>
            </value>
            <value>
                <fullName>FHA</fullName>
            </value>
            <value>
                <fullName>Jumbo</fullName>
            </value>
            <value>
                <fullName>VA</fullName>
            </value>
            <value>
                <fullName>NonQM</fullName>
            </value>
            <value>
                <fullName>HELOC</fullName>
            </value>
            <value>
                <fullName>USDA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>DPA 2nd</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Address__c.field-meta.xml
<CustomField>
    <fullName>Property_Address__c</fullName>
    <label>Property Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>Property City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Postal_Code__c</fullName>
    <label>Property Postal Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>Property State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Property_Type__c</fullName>
    <label>Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single Family</fullName>
            </value>
            <value>
                <fullName>Condo</fullName>
            </value>
            <value>
                <fullName>Town House</fullName>
            </value>
            <value>
                <fullName>1 Unit</fullName>
            </value>
            <value>
                <fullName>2-4 Units</fullName>
            </value>
            <value>
                <fullName>4-10 Units</fullName>
            </value>
            <value>
                <fullName>10+ Units</fullName>
            </value>
            <value>
                <fullName>PUD</fullName>
            </value>
            <value>
                <fullName>Mobile Home</fullName>
            </value>
            <value>
                <fullName>Land</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Submission_Form_Date__c.field-meta.xml
<CustomField>
    <fullName>Submission_Form_Date__c</fullName>
    <label>Submission Form Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/ValueLink_Appraisal_Type__c.field-meta.xml
<CustomField>
    <fullName>ValueLink_Appraisal_Type__c</fullName>
    <label>ValueLink Appraisal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1004 Conventional</fullName>
            </value>
            <value>
                <fullName>1004 plus 1007</fullName>
            </value>
            <value>
                <fullName>1004 plus 216</fullName>
            </value>
            <value>
                <fullName>1004 plus 216 and 1007</fullName>
            </value>
            <value>
                <fullName>1004 Conventional (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1004 plus 216 and 1007 (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1004 FHA</fullName>
            </value>
            <value>
                <fullName>1004 FHA Flip</fullName>
            </value>
            <value>
                <fullName>1004 plus 1007 FHA</fullName>
            </value>
            <value>
                <fullName>1004 plus 216 and 1007 FHA</fullName>
            </value>
            <value>
                <fullName>1004 plus 216 and 1007 FHA (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1004 FHA (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1004- Super Jumbo</fullName>
            </value>
            <value>
                <fullName>1073 Conventional</fullName>
            </value>
            <value>
                <fullName>1073 plus 1007</fullName>
            </value>
            <value>
                <fullName>1073 plus 216 and 1007</fullName>
            </value>
            <value>
                <fullName>1073 Conventional (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1073 Conv (Complex/Jumbo) plus 1007</fullName>
            </value>
            <value>
                <fullName>1073 FHA</fullName>
            </value>
            <value>
                <fullName>1073 FHA Flip</fullName>
            </value>
            <value>
                <fullName>1073 plus 1007 and 216 FHA</fullName>
            </value>
            <value>
                <fullName>1073 FHA (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1025 Small Residential Conventional</fullName>
            </value>
            <value>
                <fullName>1025 Small Residential plus 216</fullName>
            </value>
            <value>
                <fullName>1025 W/ REO addendum</fullName>
            </value>
            <value>
                <fullName>1025 Conventional (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1025 Small Residential FHA</fullName>
            </value>
            <value>
                <fullName>1025 FHA (Complex/ Jumbo)</fullName>
            </value>
            <value>
                <fullName>1004C - Conventional</fullName>
            </value>
            <value>
                <fullName>1004C w/ 1007</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Wire_Notes__c.field-meta.xml
<CustomField>
    <fullName>Wire_Notes__c</fullName>
    <label>Wire Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Loan.cls
public with sharing class Loan extends PersistentObject{
    private Transaction__c data;
    public SObject getDataAsSObject(){
        return (SObject)this.data;
    }
    public Loan(Transaction__c opp){
        this.data = opp;
        setPersistenceStrategy(new PersistenceStrategy.BasicSave());
    }
    public Transaction__c getData(){
        return this.data;
    }
    public String getActiveAppraisalID(){
        return this.data.Appraisal_Order__c;
    }
    public String getLoanType(){
        return this.data.Loan_Type_1st_TD__c;
    }
    public String getProcessorName(){
        return this.data.Additional_Processor__c;
    }
    public String getLoanPurpose(){
        return this.data.Loan_Purpose__c;
    }
    public String getPropertyType(){
        return this.data.Property_Type__c;
    }
    public String getLoanNumber(){
        return this.data.Loan_Number__c;
    }
    public String getPropertyCity(){
        return this.data.Property_City__c;
    }
    public String getPropertyZipcode(){
        return this.data.Property_Postal_Code__c;
    }
    public String getPropertyState(){
        return this.data.Property_State__c;
    }
    public String getPropertyStreet(){
        return this.data.Property_Address__c;
    }
    public String getPropertyCounty(){
        return this.data.County__c;
    }
    public String getAppraisalType(){
        return this.data.ValueLink_Appraisal_Type__c;
    }
    public String getFHACaseNumber(){
        return this.data.FHA_Case_Number__c;
    }
    public Datetime getSubmissionFormGeneratedDate(){
        return this.data.Submission_Form_Date__c;
    }
    public String getPrimaryBorrowerEmail(){ 
		return this.data.Borrower_Name__r.PersonEmail;
	}
    public String getPersonAccountId(){
        return this.data.Borrower_Name__c;
    }
    public String getOneDriveLink(){
        return this.data.Conditions_One_Drive_Link__c;
    }
	
//    public String getSubmissionNotes(){
//        return this.data.Submission_Notes__c;
//    }
    public Id getId(){
        return this.data.Id;
    }
    public Id getOwnerId(){
        return this.data.OwnerId;
    }
    public String getOwnerEmail(){
        return this.data.Owner.Email;
    }
    public void setFedExTenderedDate(Date dtime){
        this.data.FedEx_Labels_Received__c = dtime;
    }
    
//    public String getWireNotes(){
//        return this.data.Wire_Notes__c;
//    }
    public String getPrimaryBorrowerName(){
        return this.data.Borrower_First_Name__c + ' ' + this.data.Borrower_Last_Name__c;
    }
    public String getBorrowerName(){
        return this.data.Borrower_Name__r.Name;
    }
    public String getPrimaryBorrowerFirstName(){
        return this.data.Borrower_First_Name__c;
    }
    public String getPrimaryBorrowerLastName(){
        return this.data.Borrower_Last_Name__c;
    }
    public String getPrimaryBorrowerPhone(){
        return this.data.Borrowers_Phone__c;
    }
//    public Decimal getLoanAmount(){
//        return this.data.Loan_Amount__c;
//    }
//    public void setSubmissionFormGeneratedDate(Datetime dt){
//        this.data.Submission_Form_Date__c = dt;
//    }
//    public void setStageAndWorkflowStatus(String status, String workflow){
//        this.data.StageName=status;
//        this.data.Workflow_Status__c=workflow;
//    }
    public override void persist(){
        if(this.getPersistenceStrategy()==null){
            upsert this.data;
        }else{
            this.getPersistenceStrategy().persist(data);
        }
    }
}