force-app/main/default/objects/Appraisal_Order__c/Appraisal_Order__c.object-meta.xml
<CustomObject>
    <label>Appraisal Order</label>
    <nameField>
        <displayFormat>AO-{00000}</displayFormat>
        <label>Appraisal Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appraisal Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appraisal_Order__c/fields/Loan__c.field-meta.xml
<CustomField>
    <fullName>Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Appraisal Orders</relationshipLabel>
    <relationshipName>Appraisal_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appraisal_Order__c/fields/Order_ID__c.field-meta.xml
<CustomField>
    <fullName>Order_ID__c</fullName>
    <label>Order ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Appraisal_Order__c.field-meta.xml
<CustomField>
    <fullName>Appraisal_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Appraisal Order</label>
    <referenceTo>Appraisal_Order__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ValueLinkDataFetchTests.cls
@IsTest
public class ValueLinkDataFetchTests {
    
    public class MockHttpResponseGenerator implements HttpCalloutMock {

        public HTTPResponse respond(HTTPRequest req) {
            
            String reqBody = req.getBodyAsBlob().toString();
            HttpResponse res = new HttpResponse();
            
            if (reqBody.contains('GetOrderStatus')) {
                res.setBody('<VLOrderStatus><OrderStatusID>6</OrderStatusID><OrderStatusName>Completed</OrderStatusName></VLOrderStatus>');
            } else {
                res.setBody('<ANY><ReportName>ANYBLOBDATA</ReportName><Report>TestFileName</Report></ANY>');
            }
            
            res.setStatusCode(200);
            return res;
        }
    }

    @IsTest static void testFetchQueueable() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        Transaction__c t = new Transaction__c();
        insert t;
        
        Appraisal_Order__c o = new Appraisal_Order__c(Loan__c = t.Id, Order_Id__c = 'ORDERID');
        insert o;
        
        Test.startTest();
        ValueLinkDataFetchQueueable.fetchReports(new List<String> { 'ORDERID' });
        Test.stopTest();
    }
    
}